package com.gh.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class BaseUserRoleExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table GHPORT.BASE_USER_ROLE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table GHPORT.BASE_USER_ROLE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.BASE_USER_ROLE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public BaseUserRoleExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.BASE_USER_ROLE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	protected BaseUserRoleExample(BaseUserRoleExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.BASE_USER_ROLE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.BASE_USER_ROLE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.BASE_USER_ROLE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.BASE_USER_ROLE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.BASE_USER_ROLE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.BASE_USER_ROLE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.BASE_USER_ROLE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table GHPORT.BASE_USER_ROLE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andFuidIsNull() {
			addCriterion("FUID is null");
			return this;
		}

		public Criteria andFuidIsNotNull() {
			addCriterion("FUID is not null");
			return this;
		}

		public Criteria andFuidEqualTo(String value) {
			addCriterion("FUID =", value, "fuid");
			return this;
		}

		public Criteria andFuidNotEqualTo(String value) {
			addCriterion("FUID <>", value, "fuid");
			return this;
		}

		public Criteria andFuidGreaterThan(String value) {
			addCriterion("FUID >", value, "fuid");
			return this;
		}

		public Criteria andFuidGreaterThanOrEqualTo(String value) {
			addCriterion("FUID >=", value, "fuid");
			return this;
		}

		public Criteria andFuidLessThan(String value) {
			addCriterion("FUID <", value, "fuid");
			return this;
		}

		public Criteria andFuidLessThanOrEqualTo(String value) {
			addCriterion("FUID <=", value, "fuid");
			return this;
		}

		public Criteria andFuidLike(String value) {
			addCriterion("FUID like", value, "fuid");
			return this;
		}

		public Criteria andFuidNotLike(String value) {
			addCriterion("FUID not like", value, "fuid");
			return this;
		}

		public Criteria andFuidIn(List values) {
			addCriterion("FUID in", values, "fuid");
			return this;
		}

		public Criteria andFuidNotIn(List values) {
			addCriterion("FUID not in", values, "fuid");
			return this;
		}

		public Criteria andFuidBetween(String value1, String value2) {
			addCriterion("FUID between", value1, value2, "fuid");
			return this;
		}

		public Criteria andFuidNotBetween(String value1, String value2) {
			addCriterion("FUID not between", value1, value2, "fuid");
			return this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("USERID is null");
			return this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("USERID is not null");
			return this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("USERID =", value, "userid");
			return this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("USERID <>", value, "userid");
			return this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("USERID >", value, "userid");
			return this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("USERID >=", value, "userid");
			return this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("USERID <", value, "userid");
			return this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("USERID <=", value, "userid");
			return this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("USERID like", value, "userid");
			return this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("USERID not like", value, "userid");
			return this;
		}

		public Criteria andUseridIn(List values) {
			addCriterion("USERID in", values, "userid");
			return this;
		}

		public Criteria andUseridNotIn(List values) {
			addCriterion("USERID not in", values, "userid");
			return this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("USERID between", value1, value2, "userid");
			return this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("USERID not between", value1, value2, "userid");
			return this;
		}

		public Criteria andRoleidIsNull() {
			addCriterion("ROLEID is null");
			return this;
		}

		public Criteria andRoleidIsNotNull() {
			addCriterion("ROLEID is not null");
			return this;
		}

		public Criteria andRoleidEqualTo(String value) {
			addCriterion("ROLEID =", value, "roleid");
			return this;
		}

		public Criteria andRoleidNotEqualTo(String value) {
			addCriterion("ROLEID <>", value, "roleid");
			return this;
		}

		public Criteria andRoleidGreaterThan(String value) {
			addCriterion("ROLEID >", value, "roleid");
			return this;
		}

		public Criteria andRoleidGreaterThanOrEqualTo(String value) {
			addCriterion("ROLEID >=", value, "roleid");
			return this;
		}

		public Criteria andRoleidLessThan(String value) {
			addCriterion("ROLEID <", value, "roleid");
			return this;
		}

		public Criteria andRoleidLessThanOrEqualTo(String value) {
			addCriterion("ROLEID <=", value, "roleid");
			return this;
		}

		public Criteria andRoleidLike(String value) {
			addCriterion("ROLEID like", value, "roleid");
			return this;
		}

		public Criteria andRoleidNotLike(String value) {
			addCriterion("ROLEID not like", value, "roleid");
			return this;
		}

		public Criteria andRoleidIn(List values) {
			addCriterion("ROLEID in", values, "roleid");
			return this;
		}

		public Criteria andRoleidNotIn(List values) {
			addCriterion("ROLEID not in", values, "roleid");
			return this;
		}

		public Criteria andRoleidBetween(String value1, String value2) {
			addCriterion("ROLEID between", value1, value2, "roleid");
			return this;
		}

		public Criteria andRoleidNotBetween(String value1, String value2) {
			addCriterion("ROLEID not between", value1, value2, "roleid");
			return this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("CREATEDATE is null");
			return this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("CREATEDATE is not null");
			return this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterionForJDBCDate("CREATEDATE =", value, "createdate");
			return this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterionForJDBCDate("CREATEDATE <>", value, "createdate");
			return this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterionForJDBCDate("CREATEDATE >", value, "createdate");
			return this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATEDATE >=", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterionForJDBCDate("CREATEDATE <", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("CREATEDATE <=", value, "createdate");
			return this;
		}

		public Criteria andCreatedateIn(List values) {
			addCriterionForJDBCDate("CREATEDATE in", values, "createdate");
			return this;
		}

		public Criteria andCreatedateNotIn(List values) {
			addCriterionForJDBCDate("CREATEDATE not in", values, "createdate");
			return this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATEDATE between", value1, value2, "createdate");
			return this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("CREATEDATE not between", value1, value2, "createdate");
			return this;
		}

		public Criteria andCreateuseridIsNull() {
			addCriterion("CREATEUSERID is null");
			return this;
		}

		public Criteria andCreateuseridIsNotNull() {
			addCriterion("CREATEUSERID is not null");
			return this;
		}

		public Criteria andCreateuseridEqualTo(String value) {
			addCriterion("CREATEUSERID =", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridNotEqualTo(String value) {
			addCriterion("CREATEUSERID <>", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridGreaterThan(String value) {
			addCriterion("CREATEUSERID >", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridGreaterThanOrEqualTo(String value) {
			addCriterion("CREATEUSERID >=", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridLessThan(String value) {
			addCriterion("CREATEUSERID <", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridLessThanOrEqualTo(String value) {
			addCriterion("CREATEUSERID <=", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridLike(String value) {
			addCriterion("CREATEUSERID like", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridNotLike(String value) {
			addCriterion("CREATEUSERID not like", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridIn(List values) {
			addCriterion("CREATEUSERID in", values, "createuserid");
			return this;
		}

		public Criteria andCreateuseridNotIn(List values) {
			addCriterion("CREATEUSERID not in", values, "createuserid");
			return this;
		}

		public Criteria andCreateuseridBetween(String value1, String value2) {
			addCriterion("CREATEUSERID between", value1, value2, "createuserid");
			return this;
		}

		public Criteria andCreateuseridNotBetween(String value1, String value2) {
			addCriterion("CREATEUSERID not between", value1, value2, "createuserid");
			return this;
		}

		public Criteria andCreateuserrealnameIsNull() {
			addCriterion("CREATEUSERREALNAME is null");
			return this;
		}

		public Criteria andCreateuserrealnameIsNotNull() {
			addCriterion("CREATEUSERREALNAME is not null");
			return this;
		}

		public Criteria andCreateuserrealnameEqualTo(String value) {
			addCriterion("CREATEUSERREALNAME =", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameNotEqualTo(String value) {
			addCriterion("CREATEUSERREALNAME <>", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameGreaterThan(String value) {
			addCriterion("CREATEUSERREALNAME >", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameGreaterThanOrEqualTo(String value) {
			addCriterion("CREATEUSERREALNAME >=", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameLessThan(String value) {
			addCriterion("CREATEUSERREALNAME <", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameLessThanOrEqualTo(String value) {
			addCriterion("CREATEUSERREALNAME <=", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameLike(String value) {
			addCriterion("CREATEUSERREALNAME like", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameNotLike(String value) {
			addCriterion("CREATEUSERREALNAME not like", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameIn(List values) {
			addCriterion("CREATEUSERREALNAME in", values, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameNotIn(List values) {
			addCriterion("CREATEUSERREALNAME not in", values, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameBetween(String value1, String value2) {
			addCriterion("CREATEUSERREALNAME between", value1, value2, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameNotBetween(String value1, String value2) {
			addCriterion("CREATEUSERREALNAME not between", value1, value2, "createuserrealname");
			return this;
		}

		public Criteria andModifydateIsNull() {
			addCriterion("MODIFYDATE is null");
			return this;
		}

		public Criteria andModifydateIsNotNull() {
			addCriterion("MODIFYDATE is not null");
			return this;
		}

		public Criteria andModifydateEqualTo(Date value) {
			addCriterionForJDBCDate("MODIFYDATE =", value, "modifydate");
			return this;
		}

		public Criteria andModifydateNotEqualTo(Date value) {
			addCriterionForJDBCDate("MODIFYDATE <>", value, "modifydate");
			return this;
		}

		public Criteria andModifydateGreaterThan(Date value) {
			addCriterionForJDBCDate("MODIFYDATE >", value, "modifydate");
			return this;
		}

		public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("MODIFYDATE >=", value, "modifydate");
			return this;
		}

		public Criteria andModifydateLessThan(Date value) {
			addCriterionForJDBCDate("MODIFYDATE <", value, "modifydate");
			return this;
		}

		public Criteria andModifydateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("MODIFYDATE <=", value, "modifydate");
			return this;
		}

		public Criteria andModifydateIn(List values) {
			addCriterionForJDBCDate("MODIFYDATE in", values, "modifydate");
			return this;
		}

		public Criteria andModifydateNotIn(List values) {
			addCriterionForJDBCDate("MODIFYDATE not in", values, "modifydate");
			return this;
		}

		public Criteria andModifydateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("MODIFYDATE between", value1, value2, "modifydate");
			return this;
		}

		public Criteria andModifydateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("MODIFYDATE not between", value1, value2, "modifydate");
			return this;
		}

		public Criteria andModifyuseridIsNull() {
			addCriterion("MODIFYUSERID is null");
			return this;
		}

		public Criteria andModifyuseridIsNotNull() {
			addCriterion("MODIFYUSERID is not null");
			return this;
		}

		public Criteria andModifyuseridEqualTo(String value) {
			addCriterion("MODIFYUSERID =", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridNotEqualTo(String value) {
			addCriterion("MODIFYUSERID <>", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridGreaterThan(String value) {
			addCriterion("MODIFYUSERID >", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFYUSERID >=", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridLessThan(String value) {
			addCriterion("MODIFYUSERID <", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridLessThanOrEqualTo(String value) {
			addCriterion("MODIFYUSERID <=", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridLike(String value) {
			addCriterion("MODIFYUSERID like", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridNotLike(String value) {
			addCriterion("MODIFYUSERID not like", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridIn(List values) {
			addCriterion("MODIFYUSERID in", values, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridNotIn(List values) {
			addCriterion("MODIFYUSERID not in", values, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridBetween(String value1, String value2) {
			addCriterion("MODIFYUSERID between", value1, value2, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridNotBetween(String value1, String value2) {
			addCriterion("MODIFYUSERID not between", value1, value2, "modifyuserid");
			return this;
		}

		public Criteria andModifyuserrealnameIsNull() {
			addCriterion("MODIFYUSERREALNAME is null");
			return this;
		}

		public Criteria andModifyuserrealnameIsNotNull() {
			addCriterion("MODIFYUSERREALNAME is not null");
			return this;
		}

		public Criteria andModifyuserrealnameEqualTo(String value) {
			addCriterion("MODIFYUSERREALNAME =", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameNotEqualTo(String value) {
			addCriterion("MODIFYUSERREALNAME <>", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameGreaterThan(String value) {
			addCriterion("MODIFYUSERREALNAME >", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFYUSERREALNAME >=", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameLessThan(String value) {
			addCriterion("MODIFYUSERREALNAME <", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameLessThanOrEqualTo(String value) {
			addCriterion("MODIFYUSERREALNAME <=", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameLike(String value) {
			addCriterion("MODIFYUSERREALNAME like", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameNotLike(String value) {
			addCriterion("MODIFYUSERREALNAME not like", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameIn(List values) {
			addCriterion("MODIFYUSERREALNAME in", values, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameNotIn(List values) {
			addCriterion("MODIFYUSERREALNAME not in", values, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameBetween(String value1, String value2) {
			addCriterion("MODIFYUSERREALNAME between", value1, value2, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameNotBetween(String value1, String value2) {
			addCriterion("MODIFYUSERREALNAME not between", value1, value2, "modifyuserrealname");
			return this;
		}
	}
}