package com.gh.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BaseOrganize {
    /**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.FUID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String fuid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.PARENTID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String parentid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.CODE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String code;
	
	private String emergency;
	
	private String iscargo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.FULLNAME
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String fullname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.LAYER
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private int layer;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.OUTERPHONE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String outerphone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.INNERPHONE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String innerphone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.MANAGER
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String manager;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.DELETEMARK
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private int deletemark;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.ENABLED
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private int enabled;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.SORTCODE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private int sortcode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.DESCRIPTION
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String description;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.CREATEDATE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private Date createdate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.CREATEUSERID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String createuserid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.CREATEUSERREALNAME
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String createuserrealname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.MODIFYDATE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private Date modifydate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.MODIFYUSERID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String modifyuserid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.MODIFYUSERREALNAME
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String modifyuserrealname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.ADDRESS
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String address;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.BUSINESSLICENSE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String businesslicense;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.MANAGERID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String managerid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.REGISTEREDCAPITAL
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private BigDecimal registeredcapital;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.CONTACT
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String contact;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.EMAIL
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String email;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.FAX
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String fax;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.OPERATINGAREA
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String operatingarea;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE.POSSONOAPPLICARE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	private String possonoapplicare;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.FUID
	 * @return  the value of GHPORT.BASE_ORGANIZE.FUID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getFuid() {
		return fuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.FUID
	 * @param fuid  the value for GHPORT.BASE_ORGANIZE.FUID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setFuid(String fuid) {
		this.fuid = fuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.PARENTID
	 * @return  the value of GHPORT.BASE_ORGANIZE.PARENTID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.PARENTID
	 * @param parentid  the value for GHPORT.BASE_ORGANIZE.PARENTID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.CODE
	 * @return  the value of GHPORT.BASE_ORGANIZE.CODE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.CODE
	 * @param code  the value for GHPORT.BASE_ORGANIZE.CODE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.FULLNAME
	 * @return  the value of GHPORT.BASE_ORGANIZE.FULLNAME
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.FULLNAME
	 * @param fullname  the value for GHPORT.BASE_ORGANIZE.FULLNAME
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.LAYER
	 * @return  the value of GHPORT.BASE_ORGANIZE.LAYER
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.OUTERPHONE
	 * @return  the value of GHPORT.BASE_ORGANIZE.OUTERPHONE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getOuterphone() {
		return outerphone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.OUTERPHONE
	 * @param outerphone  the value for GHPORT.BASE_ORGANIZE.OUTERPHONE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setOuterphone(String outerphone) {
		this.outerphone = outerphone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.INNERPHONE
	 * @return  the value of GHPORT.BASE_ORGANIZE.INNERPHONE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getInnerphone() {
		return innerphone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.INNERPHONE
	 * @param innerphone  the value for GHPORT.BASE_ORGANIZE.INNERPHONE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setInnerphone(String innerphone) {
		this.innerphone = innerphone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.MANAGER
	 * @return  the value of GHPORT.BASE_ORGANIZE.MANAGER
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getManager() {
		return manager;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.MANAGER
	 * @param manager  the value for GHPORT.BASE_ORGANIZE.MANAGER
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setManager(String manager) {
		this.manager = manager;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.DELETEMARK
	 * @return  the value of GHPORT.BASE_ORGANIZE.DELETEMARK
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.ENABLED
	 * @return  the value of GHPORT.BASE_ORGANIZE.ENABLED
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.DESCRIPTION
	 * @return  the value of GHPORT.BASE_ORGANIZE.DESCRIPTION
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.DESCRIPTION
	 * @param description  the value for GHPORT.BASE_ORGANIZE.DESCRIPTION
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.CREATEDATE
	 * @return  the value of GHPORT.BASE_ORGANIZE.CREATEDATE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.CREATEDATE
	 * @param createdate  the value for GHPORT.BASE_ORGANIZE.CREATEDATE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.CREATEUSERID
	 * @return  the value of GHPORT.BASE_ORGANIZE.CREATEUSERID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getCreateuserid() {
		return createuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.CREATEUSERID
	 * @param createuserid  the value for GHPORT.BASE_ORGANIZE.CREATEUSERID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.CREATEUSERREALNAME
	 * @return  the value of GHPORT.BASE_ORGANIZE.CREATEUSERREALNAME
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getCreateuserrealname() {
		return createuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.CREATEUSERREALNAME
	 * @param createuserrealname  the value for GHPORT.BASE_ORGANIZE.CREATEUSERREALNAME
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setCreateuserrealname(String createuserrealname) {
		this.createuserrealname = createuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.MODIFYDATE
	 * @return  the value of GHPORT.BASE_ORGANIZE.MODIFYDATE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.MODIFYDATE
	 * @param modifydate  the value for GHPORT.BASE_ORGANIZE.MODIFYDATE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.MODIFYUSERID
	 * @return  the value of GHPORT.BASE_ORGANIZE.MODIFYUSERID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getModifyuserid() {
		return modifyuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.MODIFYUSERID
	 * @param modifyuserid  the value for GHPORT.BASE_ORGANIZE.MODIFYUSERID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setModifyuserid(String modifyuserid) {
		this.modifyuserid = modifyuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.MODIFYUSERREALNAME
	 * @return  the value of GHPORT.BASE_ORGANIZE.MODIFYUSERREALNAME
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getModifyuserrealname() {
		return modifyuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.MODIFYUSERREALNAME
	 * @param modifyuserrealname  the value for GHPORT.BASE_ORGANIZE.MODIFYUSERREALNAME
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setModifyuserrealname(String modifyuserrealname) {
		this.modifyuserrealname = modifyuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.ADDRESS
	 * @return  the value of GHPORT.BASE_ORGANIZE.ADDRESS
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.ADDRESS
	 * @param address  the value for GHPORT.BASE_ORGANIZE.ADDRESS
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.BUSINESSLICENSE
	 * @return  the value of GHPORT.BASE_ORGANIZE.BUSINESSLICENSE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getBusinesslicense() {
		return businesslicense;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.BUSINESSLICENSE
	 * @param businesslicense  the value for GHPORT.BASE_ORGANIZE.BUSINESSLICENSE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setBusinesslicense(String businesslicense) {
		this.businesslicense = businesslicense;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.MANAGERID
	 * @return  the value of GHPORT.BASE_ORGANIZE.MANAGERID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getManagerid() {
		return managerid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.MANAGERID
	 * @param managerid  the value for GHPORT.BASE_ORGANIZE.MANAGERID
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setManagerid(String managerid) {
		this.managerid = managerid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.REGISTEREDCAPITAL
	 * @return  the value of GHPORT.BASE_ORGANIZE.REGISTEREDCAPITAL
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public BigDecimal getRegisteredcapital() {
		return registeredcapital;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.REGISTEREDCAPITAL
	 * @param registeredcapital  the value for GHPORT.BASE_ORGANIZE.REGISTEREDCAPITAL
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setRegisteredcapital(BigDecimal registeredcapital) {
		this.registeredcapital = registeredcapital;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.CONTACT
	 * @return  the value of GHPORT.BASE_ORGANIZE.CONTACT
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.CONTACT
	 * @param contact  the value for GHPORT.BASE_ORGANIZE.CONTACT
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.EMAIL
	 * @return  the value of GHPORT.BASE_ORGANIZE.EMAIL
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.EMAIL
	 * @param email  the value for GHPORT.BASE_ORGANIZE.EMAIL
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.FAX
	 * @return  the value of GHPORT.BASE_ORGANIZE.FAX
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.FAX
	 * @param fax  the value for GHPORT.BASE_ORGANIZE.FAX
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.OPERATINGAREA
	 * @return  the value of GHPORT.BASE_ORGANIZE.OPERATINGAREA
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getOperatingarea() {
		return operatingarea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.OPERATINGAREA
	 * @param operatingarea  the value for GHPORT.BASE_ORGANIZE.OPERATINGAREA
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setOperatingarea(String operatingarea) {
		this.operatingarea = operatingarea;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE.POSSONOAPPLICARE
	 * @return  the value of GHPORT.BASE_ORGANIZE.POSSONOAPPLICARE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public String getPossonoapplicare() {
		return possonoapplicare;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE.POSSONOAPPLICARE
	 * @param possonoapplicare  the value for GHPORT.BASE_ORGANIZE.POSSONOAPPLICARE
	 * @abatorgenerated  Mon Sep 09 14:40:50 CST 2013
	 */
	public void setPossonoapplicare(String possonoapplicare) {
		this.possonoapplicare = possonoapplicare;
	}

	//---------tree
	private String id;
	private String text;
	private Boolean checked;
	private Boolean hasChild;
	private String state;
	private String url;


    private List<Object> children=new ArrayList<Object>();

    public List<Object> getChildren() {
		return children;
	}

	public void setChildren(List<Object> children) {
		this.children = children;
	}


	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Boolean getChecked() {
		return checked;
	}

	public void setChecked(Boolean checked) {
		this.checked = checked;
	}

	public Boolean getHasChild() {
		return hasChild;
	}

	public void setHasChild(Boolean hasChild) {
		this.hasChild = hasChild;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public int getLayer() {
		return layer;
	}

	public void setLayer(int layer) {
		this.layer = layer;
	}

	public int getDeletemark() {
		return deletemark;
	}

	public void setDeletemark(int deletemark) {
		this.deletemark = deletemark;
	}

	public int getEnabled() {
		return enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

	public int getSortcode() {
		return sortcode;
	}

	public void setSortcode(int sortcode) {
		this.sortcode = sortcode;
	}

	public String getEmergency() {
		return emergency;
	}

	public void setEmergency(String emergency) {
		this.emergency = emergency;
	}

	public String getIscargo() {
		return iscargo;
	}

	public void setIscargo(String iscargo) {
		this.iscargo = iscargo;
	}
}