package com.gh.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BaseUser {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.FUID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String fuid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.CODE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String code;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.USERNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String username;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.REALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String realname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.USERADDRESSID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String useraddressid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.ROLEID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String roleid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.DEPARTMENTID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String departmentid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.DEPARTMENTNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String departmentname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.SEX
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String sex;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.MOBILE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String mobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.BIRTHDAY
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String birthday;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.TITLE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.USERPASSWORD
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String userpassword;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.QUESTION
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String question;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.ANSWERQUESTION
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String answerquestion;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.LANG
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String lang;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.THEME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String theme;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.FIRSTVISIT
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private Date firstvisit;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.PREVIOUSVISIT
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private Date previousvisit;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.LASTVISIT
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private Date lastvisit;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.LOGINCOUNT
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private int logincount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.USERONLINE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private int useronline;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.IPADDRESS
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String ipaddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.MACADDRESS
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String macaddress;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.DELETEMARK
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private int deletemark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.SORTCODE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String description;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.CREATEDATE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private Date createdate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.CREATEUSERID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String createuserid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.CREATEUSERREALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String createuserrealname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.MODIFYDATE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private Date modifydate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.MODIFYUSERID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String modifyuserid;

    private List<Object> children=new ArrayList<Object>();
    public int getLogincount() {
		return logincount;
	}

	public void setLogincount(int logincount) {
		this.logincount = logincount;
	}

	public int getUseronline() {
		return useronline;
	}

	public void setUseronline(int useronline) {
		this.useronline = useronline;
	}

	public int getDeletemark() {
		return deletemark;
	}

	public void setDeletemark(int deletemark) {
		this.deletemark = deletemark;
	}


	public List<Object> getChildren() {
		return children;
	}

	public void setChildren(List<Object> children) {
		this.children = children;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_USER.MODIFYUSERREALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String modifyuserrealname;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.FUID
     *
     * @return the value of GHPORT.BASE_USER.FUID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getFuid() {
        return fuid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.FUID
     *
     * @param fuid the value for GHPORT.BASE_USER.FUID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setFuid(String fuid) {
        this.fuid = fuid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.CODE
     *
     * @return the value of GHPORT.BASE_USER.CODE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.CODE
     *
     * @param code the value for GHPORT.BASE_USER.CODE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.USERNAME
     *
     * @return the value of GHPORT.BASE_USER.USERNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.USERNAME
     *
     * @param username the value for GHPORT.BASE_USER.USERNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.REALNAME
     *
     * @return the value of GHPORT.BASE_USER.REALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.REALNAME
     *
     * @param realname the value for GHPORT.BASE_USER.REALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.USERADDRESSID
     *
     * @return the value of GHPORT.BASE_USER.USERADDRESSID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getUseraddressid() {
        return useraddressid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.USERADDRESSID
     *
     * @param useraddressid the value for GHPORT.BASE_USER.USERADDRESSID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setUseraddressid(String useraddressid) {
        this.useraddressid = useraddressid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.ROLEID
     *
     * @return the value of GHPORT.BASE_USER.ROLEID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.ROLEID
     *
     * @param roleid the value for GHPORT.BASE_USER.ROLEID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.DEPARTMENTID
     *
     * @return the value of GHPORT.BASE_USER.DEPARTMENTID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.DEPARTMENTID
     *
     * @param departmentid the value for GHPORT.BASE_USER.DEPARTMENTID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.DEPARTMENTNAME
     *
     * @return the value of GHPORT.BASE_USER.DEPARTMENTNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.DEPARTMENTNAME
     *
     * @param departmentname the value for GHPORT.BASE_USER.DEPARTMENTNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.SEX
     *
     * @return the value of GHPORT.BASE_USER.SEX
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.SEX
     *
     * @param sex the value for GHPORT.BASE_USER.SEX
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.MOBILE
     *
     * @return the value of GHPORT.BASE_USER.MOBILE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.MOBILE
     *
     * @param mobile the value for GHPORT.BASE_USER.MOBILE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.BIRTHDAY
     *
     * @return the value of GHPORT.BASE_USER.BIRTHDAY
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.BIRTHDAY
     *
     * @param birthday the value for GHPORT.BASE_USER.BIRTHDAY
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.TITLE
     *
     * @return the value of GHPORT.BASE_USER.TITLE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.TITLE
     *
     * @param title the value for GHPORT.BASE_USER.TITLE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.USERPASSWORD
     *
     * @return the value of GHPORT.BASE_USER.USERPASSWORD
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.USERPASSWORD
     *
     * @param userpassword the value for GHPORT.BASE_USER.USERPASSWORD
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.QUESTION
     *
     * @return the value of GHPORT.BASE_USER.QUESTION
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.QUESTION
     *
     * @param question the value for GHPORT.BASE_USER.QUESTION
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.ANSWERQUESTION
     *
     * @return the value of GHPORT.BASE_USER.ANSWERQUESTION
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getAnswerquestion() {
        return answerquestion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.ANSWERQUESTION
     *
     * @param answerquestion the value for GHPORT.BASE_USER.ANSWERQUESTION
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setAnswerquestion(String answerquestion) {
        this.answerquestion = answerquestion;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.LANG
     *
     * @return the value of GHPORT.BASE_USER.LANG
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getLang() {
        return lang;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.LANG
     *
     * @param lang the value for GHPORT.BASE_USER.LANG
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setLang(String lang) {
        this.lang = lang;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.THEME
     *
     * @return the value of GHPORT.BASE_USER.THEME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.THEME
     *
     * @param theme the value for GHPORT.BASE_USER.THEME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setTheme(String theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.FIRSTVISIT
     *
     * @return the value of GHPORT.BASE_USER.FIRSTVISIT
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public Date getFirstvisit() {
        return firstvisit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.FIRSTVISIT
     *
     * @param firstvisit the value for GHPORT.BASE_USER.FIRSTVISIT
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setFirstvisit(Date firstvisit) {
        this.firstvisit = firstvisit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.PREVIOUSVISIT
     *
     * @return the value of GHPORT.BASE_USER.PREVIOUSVISIT
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public Date getPreviousvisit() {
        return previousvisit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.PREVIOUSVISIT
     *
     * @param previousvisit the value for GHPORT.BASE_USER.PREVIOUSVISIT
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setPreviousvisit(Date previousvisit) {
        this.previousvisit = previousvisit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.LASTVISIT
     *
     * @return the value of GHPORT.BASE_USER.LASTVISIT
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public Date getLastvisit() {
        return lastvisit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.LASTVISIT
     *
     * @param lastvisit the value for GHPORT.BASE_USER.LASTVISIT
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setLastvisit(Date lastvisit) {
        this.lastvisit = lastvisit;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.LOGINCOUNT
     *
     * @return the value of GHPORT.BASE_USER.LOGINCOUNT
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getIpaddress() {
        return ipaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.IPADDRESS
     *
     * @param ipaddress the value for GHPORT.BASE_USER.IPADDRESS
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.MACADDRESS
     *
     * @return the value of GHPORT.BASE_USER.MACADDRESS
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getMacaddress() {
        return macaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.MACADDRESS
     *
     * @param macaddress the value for GHPORT.BASE_USER.MACADDRESS
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.DELETEMARK
     *
     * @return the value of GHPORT.BASE_USER.DELETEMARK
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.DESCRIPTION
     *
     * @param description the value for GHPORT.BASE_USER.DESCRIPTION
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.CREATEDATE
     *
     * @return the value of GHPORT.BASE_USER.CREATEDATE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.CREATEDATE
     *
     * @param createdate the value for GHPORT.BASE_USER.CREATEDATE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.CREATEUSERID
     *
     * @return the value of GHPORT.BASE_USER.CREATEUSERID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.CREATEUSERID
     *
     * @param createuserid the value for GHPORT.BASE_USER.CREATEUSERID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.CREATEUSERREALNAME
     *
     * @return the value of GHPORT.BASE_USER.CREATEUSERREALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getCreateuserrealname() {
        return createuserrealname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.CREATEUSERREALNAME
     *
     * @param createuserrealname the value for GHPORT.BASE_USER.CREATEUSERREALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setCreateuserrealname(String createuserrealname) {
        this.createuserrealname = createuserrealname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.MODIFYDATE
     *
     * @return the value of GHPORT.BASE_USER.MODIFYDATE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.MODIFYDATE
     *
     * @param modifydate the value for GHPORT.BASE_USER.MODIFYDATE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.MODIFYUSERID
     *
     * @return the value of GHPORT.BASE_USER.MODIFYUSERID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.MODIFYUSERID
     *
     * @param modifyuserid the value for GHPORT.BASE_USER.MODIFYUSERID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setModifyuserid(String modifyuserid) {
        this.modifyuserid = modifyuserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_USER.MODIFYUSERREALNAME
     *
     * @return the value of GHPORT.BASE_USER.MODIFYUSERREALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getModifyuserrealname() {
        return modifyuserrealname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_USER.MODIFYUSERREALNAME
     *
     * @param modifyuserrealname the value for GHPORT.BASE_USER.MODIFYUSERREALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setModifyuserrealname(String modifyuserrealname) {
        this.modifyuserrealname = modifyuserrealname;
    }
}