package com.gh.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BaseScope {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.FUID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String fuid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.MENU_ID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String menuId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.ROLE_ID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String roleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.ORGANIZE_ID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String organizeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.ENABLED
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private int enabled;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.DELETEMARK
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private int deletemark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.DESCRIPTION
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String description;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.CREATEDATE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private Date createdate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.CREATEUSERREALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String createuserrealname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.CREATEUSERID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String createuserid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.MODIFYDATE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private Date modifydate;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.MODIFYUSERREALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String modifyuserrealname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.BASE_SCOPE.MODIFYUSERID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private String modifyuserid;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_SCOPE.FUID
     *
     * @return the value of GHPORT.BASE_SCOPE.FUID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    private List<Object> children=new ArrayList<Object>();
    
    public String getFuid() {
        return fuid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_SCOPE.FUID
     *
     * @param fuid the value for GHPORT.BASE_SCOPE.FUID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setFuid(String fuid) {
        this.fuid = fuid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_SCOPE.MENU_ID
     *
     * @return the value of GHPORT.BASE_SCOPE.MENU_ID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_SCOPE.MENU_ID
     *
     * @param menuId the value for GHPORT.BASE_SCOPE.MENU_ID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_SCOPE.ROLE_ID
     *
     * @return the value of GHPORT.BASE_SCOPE.ROLE_ID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_SCOPE.ROLE_ID
     *
     * @param roleId the value for GHPORT.BASE_SCOPE.ROLE_ID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_SCOPE.ORGANIZE_ID
     *
     * @return the value of GHPORT.BASE_SCOPE.ORGANIZE_ID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getOrganizeId() {
        return organizeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_SCOPE.ORGANIZE_ID
     *
     * @param organizeId the value for GHPORT.BASE_SCOPE.ORGANIZE_ID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setOrganizeId(String organizeId) {
        this.organizeId = organizeId;
    }


    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_SCOPE.DESCRIPTION
     *
     * @return the value of GHPORT.BASE_SCOPE.DESCRIPTION
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_SCOPE.DESCRIPTION
     *
     * @param description the value for GHPORT.BASE_SCOPE.DESCRIPTION
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_SCOPE.CREATEDATE
     *
     * @return the value of GHPORT.BASE_SCOPE.CREATEDATE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_SCOPE.CREATEDATE
     *
     * @param createdate the value for GHPORT.BASE_SCOPE.CREATEDATE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_SCOPE.CREATEUSERREALNAME
     *
     * @return the value of GHPORT.BASE_SCOPE.CREATEUSERREALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getCreateuserrealname() {
        return createuserrealname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_SCOPE.CREATEUSERREALNAME
     *
     * @param createuserrealname the value for GHPORT.BASE_SCOPE.CREATEUSERREALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setCreateuserrealname(String createuserrealname) {
        this.createuserrealname = createuserrealname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_SCOPE.CREATEUSERID
     *
     * @return the value of GHPORT.BASE_SCOPE.CREATEUSERID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_SCOPE.CREATEUSERID
     *
     * @param createuserid the value for GHPORT.BASE_SCOPE.CREATEUSERID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_SCOPE.MODIFYDATE
     *
     * @return the value of GHPORT.BASE_SCOPE.MODIFYDATE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_SCOPE.MODIFYDATE
     *
     * @param modifydate the value for GHPORT.BASE_SCOPE.MODIFYDATE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_SCOPE.MODIFYUSERREALNAME
     *
     * @return the value of GHPORT.BASE_SCOPE.MODIFYUSERREALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getModifyuserrealname() {
        return modifyuserrealname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_SCOPE.MODIFYUSERREALNAME
     *
     * @param modifyuserrealname the value for GHPORT.BASE_SCOPE.MODIFYUSERREALNAME
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setModifyuserrealname(String modifyuserrealname) {
        this.modifyuserrealname = modifyuserrealname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.BASE_SCOPE.MODIFYUSERID
     *
     * @return the value of GHPORT.BASE_SCOPE.MODIFYUSERID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.BASE_SCOPE.MODIFYUSERID
     *
     * @param modifyuserid the value for GHPORT.BASE_SCOPE.MODIFYUSERID
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setModifyuserid(String modifyuserid) {
        this.modifyuserid = modifyuserid;
    }

	public List<Object> getChildren() {
		return children;
	}

	public void setChildren(List<Object> children) {
		this.children = children;
	}

	public int getEnabled() {
		return enabled;
	}

	public void setEnabled(int enabled) {
		this.enabled = enabled;
	}

	public int getDeletemark() {
		return deletemark;
	}

	public void setDeletemark(int deletemark) {
		this.deletemark = deletemark;
	}
}