package com.gh.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class BaseUserExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table GHPORT.BASE_USER
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table GHPORT.BASE_USER
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_USER
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public BaseUserExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_USER
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    protected BaseUserExample(BaseUserExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_USER
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_USER
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_USER
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_USER
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_USER
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_USER
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_USER
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table GHPORT.BASE_USER
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andFuidIsNull() {
            addCriterion("FUID is null");
            return this;
        }

        public Criteria andFuidIsNotNull() {
            addCriterion("FUID is not null");
            return this;
        }

        public Criteria andFuidEqualTo(String value) {
            addCriterion("FUID =", value, "fuid");
            return this;
        }

        public Criteria andFuidNotEqualTo(String value) {
            addCriterion("FUID <>", value, "fuid");
            return this;
        }

        public Criteria andFuidGreaterThan(String value) {
            addCriterion("FUID >", value, "fuid");
            return this;
        }

        public Criteria andFuidGreaterThanOrEqualTo(String value) {
            addCriterion("FUID >=", value, "fuid");
            return this;
        }

        public Criteria andFuidLessThan(String value) {
            addCriterion("FUID <", value, "fuid");
            return this;
        }

        public Criteria andFuidLessThanOrEqualTo(String value) {
            addCriterion("FUID <=", value, "fuid");
            return this;
        }

        public Criteria andFuidLike(String value) {
            addCriterion("FUID like", value, "fuid");
            return this;
        }

        public Criteria andFuidNotLike(String value) {
            addCriterion("FUID not like", value, "fuid");
            return this;
        }

        public Criteria andFuidIn(List values) {
            addCriterion("FUID in", values, "fuid");
            return this;
        }

        public Criteria andFuidNotIn(List values) {
            addCriterion("FUID not in", values, "fuid");
            return this;
        }

        public Criteria andFuidBetween(String value1, String value2) {
            addCriterion("FUID between", value1, value2, "fuid");
            return this;
        }

        public Criteria andFuidNotBetween(String value1, String value2) {
            addCriterion("FUID not between", value1, value2, "fuid");
            return this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("CODE is null");
            return this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("CODE is not null");
            return this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("CODE =", value, "code");
            return this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("CODE <>", value, "code");
            return this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("CODE >", value, "code");
            return this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CODE >=", value, "code");
            return this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("CODE <", value, "code");
            return this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("CODE <=", value, "code");
            return this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("CODE like", value, "code");
            return this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("CODE not like", value, "code");
            return this;
        }

        public Criteria andCodeIn(List values) {
            addCriterion("CODE in", values, "code");
            return this;
        }

        public Criteria andCodeNotIn(List values) {
            addCriterion("CODE not in", values, "code");
            return this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("CODE between", value1, value2, "code");
            return this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("CODE not between", value1, value2, "code");
            return this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return this;
        }

        public Criteria andUsernameIn(List values) {
            addCriterion("USERNAME in", values, "username");
            return this;
        }

        public Criteria andUsernameNotIn(List values) {
            addCriterion("USERNAME not in", values, "username");
            return this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return this;
        }

        public Criteria andRealnameIsNull() {
            addCriterion("REALNAME is null");
            return this;
        }

        public Criteria andRealnameIsNotNull() {
            addCriterion("REALNAME is not null");
            return this;
        }

        public Criteria andRealnameEqualTo(String value) {
            addCriterion("REALNAME =", value, "realname");
            return this;
        }

        public Criteria andRealnameNotEqualTo(String value) {
            addCriterion("REALNAME <>", value, "realname");
            return this;
        }

        public Criteria andRealnameGreaterThan(String value) {
            addCriterion("REALNAME >", value, "realname");
            return this;
        }

        public Criteria andRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("REALNAME >=", value, "realname");
            return this;
        }

        public Criteria andRealnameLessThan(String value) {
            addCriterion("REALNAME <", value, "realname");
            return this;
        }

        public Criteria andRealnameLessThanOrEqualTo(String value) {
            addCriterion("REALNAME <=", value, "realname");
            return this;
        }

        public Criteria andRealnameLike(String value) {
            addCriterion("REALNAME like", value, "realname");
            return this;
        }

        public Criteria andRealnameNotLike(String value) {
            addCriterion("REALNAME not like", value, "realname");
            return this;
        }

        public Criteria andRealnameIn(List values) {
            addCriterion("REALNAME in", values, "realname");
            return this;
        }

        public Criteria andRealnameNotIn(List values) {
            addCriterion("REALNAME not in", values, "realname");
            return this;
        }

        public Criteria andRealnameBetween(String value1, String value2) {
            addCriterion("REALNAME between", value1, value2, "realname");
            return this;
        }

        public Criteria andRealnameNotBetween(String value1, String value2) {
            addCriterion("REALNAME not between", value1, value2, "realname");
            return this;
        }

        public Criteria andUseraddressidIsNull() {
            addCriterion("USERADDRESSID is null");
            return this;
        }

        public Criteria andUseraddressidIsNotNull() {
            addCriterion("USERADDRESSID is not null");
            return this;
        }

        public Criteria andUseraddressidEqualTo(String value) {
            addCriterion("USERADDRESSID =", value, "useraddressid");
            return this;
        }

        public Criteria andUseraddressidNotEqualTo(String value) {
            addCriterion("USERADDRESSID <>", value, "useraddressid");
            return this;
        }

        public Criteria andUseraddressidGreaterThan(String value) {
            addCriterion("USERADDRESSID >", value, "useraddressid");
            return this;
        }

        public Criteria andUseraddressidGreaterThanOrEqualTo(String value) {
            addCriterion("USERADDRESSID >=", value, "useraddressid");
            return this;
        }

        public Criteria andUseraddressidLessThan(String value) {
            addCriterion("USERADDRESSID <", value, "useraddressid");
            return this;
        }

        public Criteria andUseraddressidLessThanOrEqualTo(String value) {
            addCriterion("USERADDRESSID <=", value, "useraddressid");
            return this;
        }

        public Criteria andUseraddressidLike(String value) {
            addCriterion("USERADDRESSID like", value, "useraddressid");
            return this;
        }

        public Criteria andUseraddressidNotLike(String value) {
            addCriterion("USERADDRESSID not like", value, "useraddressid");
            return this;
        }

        public Criteria andUseraddressidIn(List values) {
            addCriterion("USERADDRESSID in", values, "useraddressid");
            return this;
        }

        public Criteria andUseraddressidNotIn(List values) {
            addCriterion("USERADDRESSID not in", values, "useraddressid");
            return this;
        }

        public Criteria andUseraddressidBetween(String value1, String value2) {
            addCriterion("USERADDRESSID between", value1, value2, "useraddressid");
            return this;
        }

        public Criteria andUseraddressidNotBetween(String value1, String value2) {
            addCriterion("USERADDRESSID not between", value1, value2, "useraddressid");
            return this;
        }

        public Criteria andRoleidIsNull() {
            addCriterion("ROLEID is null");
            return this;
        }

        public Criteria andRoleidIsNotNull() {
            addCriterion("ROLEID is not null");
            return this;
        }

        public Criteria andRoleidEqualTo(String value) {
            addCriterion("ROLEID =", value, "roleid");
            return this;
        }

        public Criteria andRoleidNotEqualTo(String value) {
            addCriterion("ROLEID <>", value, "roleid");
            return this;
        }

        public Criteria andRoleidGreaterThan(String value) {
            addCriterion("ROLEID >", value, "roleid");
            return this;
        }

        public Criteria andRoleidGreaterThanOrEqualTo(String value) {
            addCriterion("ROLEID >=", value, "roleid");
            return this;
        }

        public Criteria andRoleidLessThan(String value) {
            addCriterion("ROLEID <", value, "roleid");
            return this;
        }

        public Criteria andRoleidLessThanOrEqualTo(String value) {
            addCriterion("ROLEID <=", value, "roleid");
            return this;
        }

        public Criteria andRoleidLike(String value) {
            addCriterion("ROLEID like", value, "roleid");
            return this;
        }

        public Criteria andRoleidNotLike(String value) {
            addCriterion("ROLEID not like", value, "roleid");
            return this;
        }

        public Criteria andRoleidIn(List values) {
            addCriterion("ROLEID in", values, "roleid");
            return this;
        }

        public Criteria andRoleidNotIn(List values) {
            addCriterion("ROLEID not in", values, "roleid");
            return this;
        }

        public Criteria andRoleidBetween(String value1, String value2) {
            addCriterion("ROLEID between", value1, value2, "roleid");
            return this;
        }

        public Criteria andRoleidNotBetween(String value1, String value2) {
            addCriterion("ROLEID not between", value1, value2, "roleid");
            return this;
        }

        public Criteria andDepartmentidIsNull() {
            addCriterion("DEPARTMENTID is null");
            return this;
        }

        public Criteria andDepartmentidIsNotNull() {
            addCriterion("DEPARTMENTID is not null");
            return this;
        }

        public Criteria andDepartmentidEqualTo(String value) {
            addCriterion("DEPARTMENTID =", value, "departmentid");
            return this;
        }

        public Criteria andDepartmentidNotEqualTo(String value) {
            addCriterion("DEPARTMENTID <>", value, "departmentid");
            return this;
        }

        public Criteria andDepartmentidGreaterThan(String value) {
            addCriterion("DEPARTMENTID >", value, "departmentid");
            return this;
        }

        public Criteria andDepartmentidGreaterThanOrEqualTo(String value) {
            addCriterion("DEPARTMENTID >=", value, "departmentid");
            return this;
        }

        public Criteria andDepartmentidLessThan(String value) {
            addCriterion("DEPARTMENTID <", value, "departmentid");
            return this;
        }

        public Criteria andDepartmentidLessThanOrEqualTo(String value) {
            addCriterion("DEPARTMENTID <=", value, "departmentid");
            return this;
        }

        public Criteria andDepartmentidLike(String value) {
            addCriterion("DEPARTMENTID like", value, "departmentid");
            return this;
        }

        public Criteria andDepartmentidNotLike(String value) {
            addCriterion("DEPARTMENTID not like", value, "departmentid");
            return this;
        }

        public Criteria andDepartmentidIn(List values) {
            addCriterion("DEPARTMENTID in", values, "departmentid");
            return this;
        }

        public Criteria andDepartmentidNotIn(List values) {
            addCriterion("DEPARTMENTID not in", values, "departmentid");
            return this;
        }

        public Criteria andDepartmentidBetween(String value1, String value2) {
            addCriterion("DEPARTMENTID between", value1, value2, "departmentid");
            return this;
        }

        public Criteria andDepartmentidNotBetween(String value1, String value2) {
            addCriterion("DEPARTMENTID not between", value1, value2, "departmentid");
            return this;
        }

        public Criteria andDepartmentnameIsNull() {
            addCriterion("DEPARTMENTNAME is null");
            return this;
        }

        public Criteria andDepartmentnameIsNotNull() {
            addCriterion("DEPARTMENTNAME is not null");
            return this;
        }

        public Criteria andDepartmentnameEqualTo(String value) {
            addCriterion("DEPARTMENTNAME =", value, "departmentname");
            return this;
        }

        public Criteria andDepartmentnameNotEqualTo(String value) {
            addCriterion("DEPARTMENTNAME <>", value, "departmentname");
            return this;
        }

        public Criteria andDepartmentnameGreaterThan(String value) {
            addCriterion("DEPARTMENTNAME >", value, "departmentname");
            return this;
        }

        public Criteria andDepartmentnameGreaterThanOrEqualTo(String value) {
            addCriterion("DEPARTMENTNAME >=", value, "departmentname");
            return this;
        }

        public Criteria andDepartmentnameLessThan(String value) {
            addCriterion("DEPARTMENTNAME <", value, "departmentname");
            return this;
        }

        public Criteria andDepartmentnameLessThanOrEqualTo(String value) {
            addCriterion("DEPARTMENTNAME <=", value, "departmentname");
            return this;
        }

        public Criteria andDepartmentnameLike(String value) {
            addCriterion("DEPARTMENTNAME like", value, "departmentname");
            return this;
        }

        public Criteria andDepartmentnameNotLike(String value) {
            addCriterion("DEPARTMENTNAME not like", value, "departmentname");
            return this;
        }

        public Criteria andDepartmentnameIn(List values) {
            addCriterion("DEPARTMENTNAME in", values, "departmentname");
            return this;
        }

        public Criteria andDepartmentnameNotIn(List values) {
            addCriterion("DEPARTMENTNAME not in", values, "departmentname");
            return this;
        }

        public Criteria andDepartmentnameBetween(String value1, String value2) {
            addCriterion("DEPARTMENTNAME between", value1, value2, "departmentname");
            return this;
        }

        public Criteria andDepartmentnameNotBetween(String value1, String value2) {
            addCriterion("DEPARTMENTNAME not between", value1, value2, "departmentname");
            return this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("SEX =", value, "sex");
            return this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("SEX <>", value, "sex");
            return this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("SEX >", value, "sex");
            return this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("SEX >=", value, "sex");
            return this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("SEX <", value, "sex");
            return this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("SEX <=", value, "sex");
            return this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("SEX like", value, "sex");
            return this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("SEX not like", value, "sex");
            return this;
        }

        public Criteria andSexIn(List values) {
            addCriterion("SEX in", values, "sex");
            return this;
        }

        public Criteria andSexNotIn(List values) {
            addCriterion("SEX not in", values, "sex");
            return this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("MOBILE is null");
            return this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("MOBILE is not null");
            return this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("MOBILE =", value, "mobile");
            return this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("MOBILE <>", value, "mobile");
            return this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("MOBILE >", value, "mobile");
            return this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE >=", value, "mobile");
            return this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("MOBILE <", value, "mobile");
            return this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("MOBILE <=", value, "mobile");
            return this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("MOBILE like", value, "mobile");
            return this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("MOBILE not like", value, "mobile");
            return this;
        }

        public Criteria andMobileIn(List values) {
            addCriterion("MOBILE in", values, "mobile");
            return this;
        }

        public Criteria andMobileNotIn(List values) {
            addCriterion("MOBILE not in", values, "mobile");
            return this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("MOBILE between", value1, value2, "mobile");
            return this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("MOBILE not between", value1, value2, "mobile");
            return this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("BIRTHDAY is null");
            return this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("BIRTHDAY is not null");
            return this;
        }

        public Criteria andBirthdayEqualTo(String value) {
            addCriterion("BIRTHDAY =", value, "birthday");
            return this;
        }

        public Criteria andBirthdayNotEqualTo(String value) {
            addCriterion("BIRTHDAY <>", value, "birthday");
            return this;
        }

        public Criteria andBirthdayGreaterThan(String value) {
            addCriterion("BIRTHDAY >", value, "birthday");
            return this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY >=", value, "birthday");
            return this;
        }

        public Criteria andBirthdayLessThan(String value) {
            addCriterion("BIRTHDAY <", value, "birthday");
            return this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(String value) {
            addCriterion("BIRTHDAY <=", value, "birthday");
            return this;
        }

        public Criteria andBirthdayLike(String value) {
            addCriterion("BIRTHDAY like", value, "birthday");
            return this;
        }

        public Criteria andBirthdayNotLike(String value) {
            addCriterion("BIRTHDAY not like", value, "birthday");
            return this;
        }

        public Criteria andBirthdayIn(List values) {
            addCriterion("BIRTHDAY in", values, "birthday");
            return this;
        }

        public Criteria andBirthdayNotIn(List values) {
            addCriterion("BIRTHDAY not in", values, "birthday");
            return this;
        }

        public Criteria andBirthdayBetween(String value1, String value2) {
            addCriterion("BIRTHDAY between", value1, value2, "birthday");
            return this;
        }

        public Criteria andBirthdayNotBetween(String value1, String value2) {
            addCriterion("BIRTHDAY not between", value1, value2, "birthday");
            return this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("TITLE is null");
            return this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("TITLE is not null");
            return this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("TITLE =", value, "title");
            return this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("TITLE <>", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("TITLE >", value, "title");
            return this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "title");
            return this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("TITLE <", value, "title");
            return this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "title");
            return this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("TITLE like", value, "title");
            return this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("TITLE not like", value, "title");
            return this;
        }

        public Criteria andTitleIn(List values) {
            addCriterion("TITLE in", values, "title");
            return this;
        }

        public Criteria andTitleNotIn(List values) {
            addCriterion("TITLE not in", values, "title");
            return this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "title");
            return this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "title");
            return this;
        }

        public Criteria andUserpasswordIsNull() {
            addCriterion("USERPASSWORD is null");
            return this;
        }

        public Criteria andUserpasswordIsNotNull() {
            addCriterion("USERPASSWORD is not null");
            return this;
        }

        public Criteria andUserpasswordEqualTo(String value) {
            addCriterion("USERPASSWORD =", value, "userpassword");
            return this;
        }

        public Criteria andUserpasswordNotEqualTo(String value) {
            addCriterion("USERPASSWORD <>", value, "userpassword");
            return this;
        }

        public Criteria andUserpasswordGreaterThan(String value) {
            addCriterion("USERPASSWORD >", value, "userpassword");
            return this;
        }

        public Criteria andUserpasswordGreaterThanOrEqualTo(String value) {
            addCriterion("USERPASSWORD >=", value, "userpassword");
            return this;
        }

        public Criteria andUserpasswordLessThan(String value) {
            addCriterion("USERPASSWORD <", value, "userpassword");
            return this;
        }

        public Criteria andUserpasswordLessThanOrEqualTo(String value) {
            addCriterion("USERPASSWORD <=", value, "userpassword");
            return this;
        }

        public Criteria andUserpasswordLike(String value) {
            addCriterion("USERPASSWORD like", value, "userpassword");
            return this;
        }

        public Criteria andUserpasswordNotLike(String value) {
            addCriterion("USERPASSWORD not like", value, "userpassword");
            return this;
        }

        public Criteria andUserpasswordIn(List values) {
            addCriterion("USERPASSWORD in", values, "userpassword");
            return this;
        }

        public Criteria andUserpasswordNotIn(List values) {
            addCriterion("USERPASSWORD not in", values, "userpassword");
            return this;
        }

        public Criteria andUserpasswordBetween(String value1, String value2) {
            addCriterion("USERPASSWORD between", value1, value2, "userpassword");
            return this;
        }

        public Criteria andUserpasswordNotBetween(String value1, String value2) {
            addCriterion("USERPASSWORD not between", value1, value2, "userpassword");
            return this;
        }

        public Criteria andQuestionIsNull() {
            addCriterion("QUESTION is null");
            return this;
        }

        public Criteria andQuestionIsNotNull() {
            addCriterion("QUESTION is not null");
            return this;
        }

        public Criteria andQuestionEqualTo(String value) {
            addCriterion("QUESTION =", value, "question");
            return this;
        }

        public Criteria andQuestionNotEqualTo(String value) {
            addCriterion("QUESTION <>", value, "question");
            return this;
        }

        public Criteria andQuestionGreaterThan(String value) {
            addCriterion("QUESTION >", value, "question");
            return this;
        }

        public Criteria andQuestionGreaterThanOrEqualTo(String value) {
            addCriterion("QUESTION >=", value, "question");
            return this;
        }

        public Criteria andQuestionLessThan(String value) {
            addCriterion("QUESTION <", value, "question");
            return this;
        }

        public Criteria andQuestionLessThanOrEqualTo(String value) {
            addCriterion("QUESTION <=", value, "question");
            return this;
        }

        public Criteria andQuestionLike(String value) {
            addCriterion("QUESTION like", value, "question");
            return this;
        }

        public Criteria andQuestionNotLike(String value) {
            addCriterion("QUESTION not like", value, "question");
            return this;
        }

        public Criteria andQuestionIn(List values) {
            addCriterion("QUESTION in", values, "question");
            return this;
        }

        public Criteria andQuestionNotIn(List values) {
            addCriterion("QUESTION not in", values, "question");
            return this;
        }

        public Criteria andQuestionBetween(String value1, String value2) {
            addCriterion("QUESTION between", value1, value2, "question");
            return this;
        }

        public Criteria andQuestionNotBetween(String value1, String value2) {
            addCriterion("QUESTION not between", value1, value2, "question");
            return this;
        }

        public Criteria andAnswerquestionIsNull() {
            addCriterion("ANSWERQUESTION is null");
            return this;
        }

        public Criteria andAnswerquestionIsNotNull() {
            addCriterion("ANSWERQUESTION is not null");
            return this;
        }

        public Criteria andAnswerquestionEqualTo(String value) {
            addCriterion("ANSWERQUESTION =", value, "answerquestion");
            return this;
        }

        public Criteria andAnswerquestionNotEqualTo(String value) {
            addCriterion("ANSWERQUESTION <>", value, "answerquestion");
            return this;
        }

        public Criteria andAnswerquestionGreaterThan(String value) {
            addCriterion("ANSWERQUESTION >", value, "answerquestion");
            return this;
        }

        public Criteria andAnswerquestionGreaterThanOrEqualTo(String value) {
            addCriterion("ANSWERQUESTION >=", value, "answerquestion");
            return this;
        }

        public Criteria andAnswerquestionLessThan(String value) {
            addCriterion("ANSWERQUESTION <", value, "answerquestion");
            return this;
        }

        public Criteria andAnswerquestionLessThanOrEqualTo(String value) {
            addCriterion("ANSWERQUESTION <=", value, "answerquestion");
            return this;
        }

        public Criteria andAnswerquestionLike(String value) {
            addCriterion("ANSWERQUESTION like", value, "answerquestion");
            return this;
        }

        public Criteria andAnswerquestionNotLike(String value) {
            addCriterion("ANSWERQUESTION not like", value, "answerquestion");
            return this;
        }

        public Criteria andAnswerquestionIn(List values) {
            addCriterion("ANSWERQUESTION in", values, "answerquestion");
            return this;
        }

        public Criteria andAnswerquestionNotIn(List values) {
            addCriterion("ANSWERQUESTION not in", values, "answerquestion");
            return this;
        }

        public Criteria andAnswerquestionBetween(String value1, String value2) {
            addCriterion("ANSWERQUESTION between", value1, value2, "answerquestion");
            return this;
        }

        public Criteria andAnswerquestionNotBetween(String value1, String value2) {
            addCriterion("ANSWERQUESTION not between", value1, value2, "answerquestion");
            return this;
        }

        public Criteria andLangIsNull() {
            addCriterion("LANG is null");
            return this;
        }

        public Criteria andLangIsNotNull() {
            addCriterion("LANG is not null");
            return this;
        }

        public Criteria andLangEqualTo(String value) {
            addCriterion("LANG =", value, "lang");
            return this;
        }

        public Criteria andLangNotEqualTo(String value) {
            addCriterion("LANG <>", value, "lang");
            return this;
        }

        public Criteria andLangGreaterThan(String value) {
            addCriterion("LANG >", value, "lang");
            return this;
        }

        public Criteria andLangGreaterThanOrEqualTo(String value) {
            addCriterion("LANG >=", value, "lang");
            return this;
        }

        public Criteria andLangLessThan(String value) {
            addCriterion("LANG <", value, "lang");
            return this;
        }

        public Criteria andLangLessThanOrEqualTo(String value) {
            addCriterion("LANG <=", value, "lang");
            return this;
        }

        public Criteria andLangLike(String value) {
            addCriterion("LANG like", value, "lang");
            return this;
        }

        public Criteria andLangNotLike(String value) {
            addCriterion("LANG not like", value, "lang");
            return this;
        }

        public Criteria andLangIn(List values) {
            addCriterion("LANG in", values, "lang");
            return this;
        }

        public Criteria andLangNotIn(List values) {
            addCriterion("LANG not in", values, "lang");
            return this;
        }

        public Criteria andLangBetween(String value1, String value2) {
            addCriterion("LANG between", value1, value2, "lang");
            return this;
        }

        public Criteria andLangNotBetween(String value1, String value2) {
            addCriterion("LANG not between", value1, value2, "lang");
            return this;
        }

        public Criteria andThemeIsNull() {
            addCriterion("THEME is null");
            return this;
        }

        public Criteria andThemeIsNotNull() {
            addCriterion("THEME is not null");
            return this;
        }

        public Criteria andThemeEqualTo(String value) {
            addCriterion("THEME =", value, "theme");
            return this;
        }

        public Criteria andThemeNotEqualTo(String value) {
            addCriterion("THEME <>", value, "theme");
            return this;
        }

        public Criteria andThemeGreaterThan(String value) {
            addCriterion("THEME >", value, "theme");
            return this;
        }

        public Criteria andThemeGreaterThanOrEqualTo(String value) {
            addCriterion("THEME >=", value, "theme");
            return this;
        }

        public Criteria andThemeLessThan(String value) {
            addCriterion("THEME <", value, "theme");
            return this;
        }

        public Criteria andThemeLessThanOrEqualTo(String value) {
            addCriterion("THEME <=", value, "theme");
            return this;
        }

        public Criteria andThemeLike(String value) {
            addCriterion("THEME like", value, "theme");
            return this;
        }

        public Criteria andThemeNotLike(String value) {
            addCriterion("THEME not like", value, "theme");
            return this;
        }

        public Criteria andThemeIn(List values) {
            addCriterion("THEME in", values, "theme");
            return this;
        }

        public Criteria andThemeNotIn(List values) {
            addCriterion("THEME not in", values, "theme");
            return this;
        }

        public Criteria andThemeBetween(String value1, String value2) {
            addCriterion("THEME between", value1, value2, "theme");
            return this;
        }

        public Criteria andThemeNotBetween(String value1, String value2) {
            addCriterion("THEME not between", value1, value2, "theme");
            return this;
        }

        public Criteria andFirstvisitIsNull() {
            addCriterion("FIRSTVISIT is null");
            return this;
        }

        public Criteria andFirstvisitIsNotNull() {
            addCriterion("FIRSTVISIT is not null");
            return this;
        }

        public Criteria andFirstvisitEqualTo(Date value) {
            addCriterionForJDBCDate("FIRSTVISIT =", value, "firstvisit");
            return this;
        }

        public Criteria andFirstvisitNotEqualTo(Date value) {
            addCriterionForJDBCDate("FIRSTVISIT <>", value, "firstvisit");
            return this;
        }

        public Criteria andFirstvisitGreaterThan(Date value) {
            addCriterionForJDBCDate("FIRSTVISIT >", value, "firstvisit");
            return this;
        }

        public Criteria andFirstvisitGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FIRSTVISIT >=", value, "firstvisit");
            return this;
        }

        public Criteria andFirstvisitLessThan(Date value) {
            addCriterionForJDBCDate("FIRSTVISIT <", value, "firstvisit");
            return this;
        }

        public Criteria andFirstvisitLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FIRSTVISIT <=", value, "firstvisit");
            return this;
        }

        public Criteria andFirstvisitIn(List values) {
            addCriterionForJDBCDate("FIRSTVISIT in", values, "firstvisit");
            return this;
        }

        public Criteria andFirstvisitNotIn(List values) {
            addCriterionForJDBCDate("FIRSTVISIT not in", values, "firstvisit");
            return this;
        }

        public Criteria andFirstvisitBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FIRSTVISIT between", value1, value2, "firstvisit");
            return this;
        }

        public Criteria andFirstvisitNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FIRSTVISIT not between", value1, value2, "firstvisit");
            return this;
        }

        public Criteria andPreviousvisitIsNull() {
            addCriterion("PREVIOUSVISIT is null");
            return this;
        }

        public Criteria andPreviousvisitIsNotNull() {
            addCriterion("PREVIOUSVISIT is not null");
            return this;
        }

        public Criteria andPreviousvisitEqualTo(Date value) {
            addCriterionForJDBCDate("PREVIOUSVISIT =", value, "previousvisit");
            return this;
        }

        public Criteria andPreviousvisitNotEqualTo(Date value) {
            addCriterionForJDBCDate("PREVIOUSVISIT <>", value, "previousvisit");
            return this;
        }

        public Criteria andPreviousvisitGreaterThan(Date value) {
            addCriterionForJDBCDate("PREVIOUSVISIT >", value, "previousvisit");
            return this;
        }

        public Criteria andPreviousvisitGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PREVIOUSVISIT >=", value, "previousvisit");
            return this;
        }

        public Criteria andPreviousvisitLessThan(Date value) {
            addCriterionForJDBCDate("PREVIOUSVISIT <", value, "previousvisit");
            return this;
        }

        public Criteria andPreviousvisitLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PREVIOUSVISIT <=", value, "previousvisit");
            return this;
        }

        public Criteria andPreviousvisitIn(List values) {
            addCriterionForJDBCDate("PREVIOUSVISIT in", values, "previousvisit");
            return this;
        }

        public Criteria andPreviousvisitNotIn(List values) {
            addCriterionForJDBCDate("PREVIOUSVISIT not in", values, "previousvisit");
            return this;
        }

        public Criteria andPreviousvisitBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PREVIOUSVISIT between", value1, value2, "previousvisit");
            return this;
        }

        public Criteria andPreviousvisitNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PREVIOUSVISIT not between", value1, value2, "previousvisit");
            return this;
        }

        public Criteria andLastvisitIsNull() {
            addCriterion("LASTVISIT is null");
            return this;
        }

        public Criteria andLastvisitIsNotNull() {
            addCriterion("LASTVISIT is not null");
            return this;
        }

        public Criteria andLastvisitEqualTo(Date value) {
            addCriterionForJDBCDate("LASTVISIT =", value, "lastvisit");
            return this;
        }

        public Criteria andLastvisitNotEqualTo(Date value) {
            addCriterionForJDBCDate("LASTVISIT <>", value, "lastvisit");
            return this;
        }

        public Criteria andLastvisitGreaterThan(Date value) {
            addCriterionForJDBCDate("LASTVISIT >", value, "lastvisit");
            return this;
        }

        public Criteria andLastvisitGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LASTVISIT >=", value, "lastvisit");
            return this;
        }

        public Criteria andLastvisitLessThan(Date value) {
            addCriterionForJDBCDate("LASTVISIT <", value, "lastvisit");
            return this;
        }

        public Criteria andLastvisitLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("LASTVISIT <=", value, "lastvisit");
            return this;
        }

        public Criteria andLastvisitIn(List values) {
            addCriterionForJDBCDate("LASTVISIT in", values, "lastvisit");
            return this;
        }

        public Criteria andLastvisitNotIn(List values) {
            addCriterionForJDBCDate("LASTVISIT not in", values, "lastvisit");
            return this;
        }

        public Criteria andLastvisitBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LASTVISIT between", value1, value2, "lastvisit");
            return this;
        }

        public Criteria andLastvisitNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("LASTVISIT not between", value1, value2, "lastvisit");
            return this;
        }

        public Criteria andLogincountIsNull() {
            addCriterion("LOGINCOUNT is null");
            return this;
        }

        public Criteria andLogincountIsNotNull() {
            addCriterion("LOGINCOUNT is not null");
            return this;
        }

        public Criteria andLogincountEqualTo(BigDecimal value) {
            addCriterion("LOGINCOUNT =", value, "logincount");
            return this;
        }

        public Criteria andLogincountNotEqualTo(BigDecimal value) {
            addCriterion("LOGINCOUNT <>", value, "logincount");
            return this;
        }

        public Criteria andLogincountGreaterThan(BigDecimal value) {
            addCriterion("LOGINCOUNT >", value, "logincount");
            return this;
        }

        public Criteria andLogincountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LOGINCOUNT >=", value, "logincount");
            return this;
        }

        public Criteria andLogincountLessThan(BigDecimal value) {
            addCriterion("LOGINCOUNT <", value, "logincount");
            return this;
        }

        public Criteria andLogincountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LOGINCOUNT <=", value, "logincount");
            return this;
        }

        public Criteria andLogincountIn(List values) {
            addCriterion("LOGINCOUNT in", values, "logincount");
            return this;
        }

        public Criteria andLogincountNotIn(List values) {
            addCriterion("LOGINCOUNT not in", values, "logincount");
            return this;
        }

        public Criteria andLogincountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOGINCOUNT between", value1, value2, "logincount");
            return this;
        }

        public Criteria andLogincountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LOGINCOUNT not between", value1, value2, "logincount");
            return this;
        }

        public Criteria andUseronlineIsNull() {
            addCriterion("USERONLINE is null");
            return this;
        }

        public Criteria andUseronlineIsNotNull() {
            addCriterion("USERONLINE is not null");
            return this;
        }

        public Criteria andUseronlineEqualTo(BigDecimal value) {
            addCriterion("USERONLINE =", value, "useronline");
            return this;
        }

        public Criteria andUseronlineNotEqualTo(BigDecimal value) {
            addCriterion("USERONLINE <>", value, "useronline");
            return this;
        }

        public Criteria andUseronlineGreaterThan(BigDecimal value) {
            addCriterion("USERONLINE >", value, "useronline");
            return this;
        }

        public Criteria andUseronlineGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USERONLINE >=", value, "useronline");
            return this;
        }

        public Criteria andUseronlineLessThan(BigDecimal value) {
            addCriterion("USERONLINE <", value, "useronline");
            return this;
        }

        public Criteria andUseronlineLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USERONLINE <=", value, "useronline");
            return this;
        }

        public Criteria andUseronlineIn(List values) {
            addCriterion("USERONLINE in", values, "useronline");
            return this;
        }

        public Criteria andUseronlineNotIn(List values) {
            addCriterion("USERONLINE not in", values, "useronline");
            return this;
        }

        public Criteria andUseronlineBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USERONLINE between", value1, value2, "useronline");
            return this;
        }

        public Criteria andUseronlineNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USERONLINE not between", value1, value2, "useronline");
            return this;
        }

        public Criteria andIpaddressIsNull() {
            addCriterion("IPADDRESS is null");
            return this;
        }

        public Criteria andIpaddressIsNotNull() {
            addCriterion("IPADDRESS is not null");
            return this;
        }

        public Criteria andIpaddressEqualTo(String value) {
            addCriterion("IPADDRESS =", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressNotEqualTo(String value) {
            addCriterion("IPADDRESS <>", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressGreaterThan(String value) {
            addCriterion("IPADDRESS >", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressGreaterThanOrEqualTo(String value) {
            addCriterion("IPADDRESS >=", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressLessThan(String value) {
            addCriterion("IPADDRESS <", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressLessThanOrEqualTo(String value) {
            addCriterion("IPADDRESS <=", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressLike(String value) {
            addCriterion("IPADDRESS like", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressNotLike(String value) {
            addCriterion("IPADDRESS not like", value, "ipaddress");
            return this;
        }

        public Criteria andIpaddressIn(List values) {
            addCriterion("IPADDRESS in", values, "ipaddress");
            return this;
        }

        public Criteria andIpaddressNotIn(List values) {
            addCriterion("IPADDRESS not in", values, "ipaddress");
            return this;
        }

        public Criteria andIpaddressBetween(String value1, String value2) {
            addCriterion("IPADDRESS between", value1, value2, "ipaddress");
            return this;
        }

        public Criteria andIpaddressNotBetween(String value1, String value2) {
            addCriterion("IPADDRESS not between", value1, value2, "ipaddress");
            return this;
        }

        public Criteria andMacaddressIsNull() {
            addCriterion("MACADDRESS is null");
            return this;
        }

        public Criteria andMacaddressIsNotNull() {
            addCriterion("MACADDRESS is not null");
            return this;
        }

        public Criteria andMacaddressEqualTo(String value) {
            addCriterion("MACADDRESS =", value, "macaddress");
            return this;
        }

        public Criteria andMacaddressNotEqualTo(String value) {
            addCriterion("MACADDRESS <>", value, "macaddress");
            return this;
        }

        public Criteria andMacaddressGreaterThan(String value) {
            addCriterion("MACADDRESS >", value, "macaddress");
            return this;
        }

        public Criteria andMacaddressGreaterThanOrEqualTo(String value) {
            addCriterion("MACADDRESS >=", value, "macaddress");
            return this;
        }

        public Criteria andMacaddressLessThan(String value) {
            addCriterion("MACADDRESS <", value, "macaddress");
            return this;
        }

        public Criteria andMacaddressLessThanOrEqualTo(String value) {
            addCriterion("MACADDRESS <=", value, "macaddress");
            return this;
        }

        public Criteria andMacaddressLike(String value) {
            addCriterion("MACADDRESS like", value, "macaddress");
            return this;
        }

        public Criteria andMacaddressNotLike(String value) {
            addCriterion("MACADDRESS not like", value, "macaddress");
            return this;
        }

        public Criteria andMacaddressIn(List values) {
            addCriterion("MACADDRESS in", values, "macaddress");
            return this;
        }

        public Criteria andMacaddressNotIn(List values) {
            addCriterion("MACADDRESS not in", values, "macaddress");
            return this;
        }

        public Criteria andMacaddressBetween(String value1, String value2) {
            addCriterion("MACADDRESS between", value1, value2, "macaddress");
            return this;
        }

        public Criteria andMacaddressNotBetween(String value1, String value2) {
            addCriterion("MACADDRESS not between", value1, value2, "macaddress");
            return this;
        }

        public Criteria andDeletemarkIsNull() {
            addCriterion("DELETEMARK is null");
            return this;
        }

        public Criteria andDeletemarkIsNotNull() {
            addCriterion("DELETEMARK is not null");
            return this;
        }

        public Criteria andDeletemarkEqualTo(BigDecimal value) {
            addCriterion("DELETEMARK =", value, "deletemark");
            return this;
        }

        public Criteria andDeletemarkNotEqualTo(BigDecimal value) {
            addCriterion("DELETEMARK <>", value, "deletemark");
            return this;
        }

        public Criteria andDeletemarkGreaterThan(BigDecimal value) {
            addCriterion("DELETEMARK >", value, "deletemark");
            return this;
        }

        public Criteria andDeletemarkGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DELETEMARK >=", value, "deletemark");
            return this;
        }

        public Criteria andDeletemarkLessThan(BigDecimal value) {
            addCriterion("DELETEMARK <", value, "deletemark");
            return this;
        }

        public Criteria andDeletemarkLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DELETEMARK <=", value, "deletemark");
            return this;
        }

        public Criteria andDeletemarkIn(List values) {
            addCriterion("DELETEMARK in", values, "deletemark");
            return this;
        }

        public Criteria andDeletemarkNotIn(List values) {
            addCriterion("DELETEMARK not in", values, "deletemark");
            return this;
        }

        public Criteria andDeletemarkBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DELETEMARK between", value1, value2, "deletemark");
            return this;
        }

        public Criteria andDeletemarkNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DELETEMARK not between", value1, value2, "deletemark");
            return this;
        }

        public Criteria andSortcodeIsNull() {
            addCriterion("SORTCODE is null");
            return this;
        }

        public Criteria andSortcodeIsNotNull() {
            addCriterion("SORTCODE is not null");
            return this;
        }

        public Criteria andSortcodeEqualTo(BigDecimal value) {
            addCriterion("SORTCODE =", value, "sortcode");
            return this;
        }

        public Criteria andSortcodeNotEqualTo(BigDecimal value) {
            addCriterion("SORTCODE <>", value, "sortcode");
            return this;
        }

        public Criteria andSortcodeGreaterThan(BigDecimal value) {
            addCriterion("SORTCODE >", value, "sortcode");
            return this;
        }

        public Criteria andSortcodeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SORTCODE >=", value, "sortcode");
            return this;
        }

        public Criteria andSortcodeLessThan(BigDecimal value) {
            addCriterion("SORTCODE <", value, "sortcode");
            return this;
        }

        public Criteria andSortcodeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SORTCODE <=", value, "sortcode");
            return this;
        }

        public Criteria andSortcodeIn(List values) {
            addCriterion("SORTCODE in", values, "sortcode");
            return this;
        }

        public Criteria andSortcodeNotIn(List values) {
            addCriterion("SORTCODE not in", values, "sortcode");
            return this;
        }

        public Criteria andSortcodeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SORTCODE between", value1, value2, "sortcode");
            return this;
        }

        public Criteria andSortcodeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SORTCODE not between", value1, value2, "sortcode");
            return this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return this;
        }

        public Criteria andDescriptionIn(List values) {
            addCriterion("DESCRIPTION in", values, "description");
            return this;
        }

        public Criteria andDescriptionNotIn(List values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE =", value, "createdate");
            return this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE <>", value, "createdate");
            return this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATEDATE >", value, "createdate");
            return this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE >=", value, "createdate");
            return this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterionForJDBCDate("CREATEDATE <", value, "createdate");
            return this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE <=", value, "createdate");
            return this;
        }

        public Criteria andCreatedateIn(List values) {
            addCriterionForJDBCDate("CREATEDATE in", values, "createdate");
            return this;
        }

        public Criteria andCreatedateNotIn(List values) {
            addCriterionForJDBCDate("CREATEDATE not in", values, "createdate");
            return this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATEDATE between", value1, value2, "createdate");
            return this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATEDATE not between", value1, value2, "createdate");
            return this;
        }

        public Criteria andCreateuseridIsNull() {
            addCriterion("CREATEUSERID is null");
            return this;
        }

        public Criteria andCreateuseridIsNotNull() {
            addCriterion("CREATEUSERID is not null");
            return this;
        }

        public Criteria andCreateuseridEqualTo(String value) {
            addCriterion("CREATEUSERID =", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridNotEqualTo(String value) {
            addCriterion("CREATEUSERID <>", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridGreaterThan(String value) {
            addCriterion("CREATEUSERID >", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSERID >=", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridLessThan(String value) {
            addCriterion("CREATEUSERID <", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSERID <=", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridLike(String value) {
            addCriterion("CREATEUSERID like", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridNotLike(String value) {
            addCriterion("CREATEUSERID not like", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridIn(List values) {
            addCriterion("CREATEUSERID in", values, "createuserid");
            return this;
        }

        public Criteria andCreateuseridNotIn(List values) {
            addCriterion("CREATEUSERID not in", values, "createuserid");
            return this;
        }

        public Criteria andCreateuseridBetween(String value1, String value2) {
            addCriterion("CREATEUSERID between", value1, value2, "createuserid");
            return this;
        }

        public Criteria andCreateuseridNotBetween(String value1, String value2) {
            addCriterion("CREATEUSERID not between", value1, value2, "createuserid");
            return this;
        }

        public Criteria andCreateuserrealnameIsNull() {
            addCriterion("CREATEUSERREALNAME is null");
            return this;
        }

        public Criteria andCreateuserrealnameIsNotNull() {
            addCriterion("CREATEUSERREALNAME is not null");
            return this;
        }

        public Criteria andCreateuserrealnameEqualTo(String value) {
            addCriterion("CREATEUSERREALNAME =", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameNotEqualTo(String value) {
            addCriterion("CREATEUSERREALNAME <>", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameGreaterThan(String value) {
            addCriterion("CREATEUSERREALNAME >", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSERREALNAME >=", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameLessThan(String value) {
            addCriterion("CREATEUSERREALNAME <", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSERREALNAME <=", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameLike(String value) {
            addCriterion("CREATEUSERREALNAME like", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameNotLike(String value) {
            addCriterion("CREATEUSERREALNAME not like", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameIn(List values) {
            addCriterion("CREATEUSERREALNAME in", values, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameNotIn(List values) {
            addCriterion("CREATEUSERREALNAME not in", values, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameBetween(String value1, String value2) {
            addCriterion("CREATEUSERREALNAME between", value1, value2, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameNotBetween(String value1, String value2) {
            addCriterion("CREATEUSERREALNAME not between", value1, value2, "createuserrealname");
            return this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("MODIFYDATE is null");
            return this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("MODIFYDATE is not null");
            return this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterionForJDBCDate("MODIFYDATE =", value, "modifydate");
            return this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterionForJDBCDate("MODIFYDATE <>", value, "modifydate");
            return this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterionForJDBCDate("MODIFYDATE >", value, "modifydate");
            return this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MODIFYDATE >=", value, "modifydate");
            return this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterionForJDBCDate("MODIFYDATE <", value, "modifydate");
            return this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MODIFYDATE <=", value, "modifydate");
            return this;
        }

        public Criteria andModifydateIn(List values) {
            addCriterionForJDBCDate("MODIFYDATE in", values, "modifydate");
            return this;
        }

        public Criteria andModifydateNotIn(List values) {
            addCriterionForJDBCDate("MODIFYDATE not in", values, "modifydate");
            return this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MODIFYDATE between", value1, value2, "modifydate");
            return this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MODIFYDATE not between", value1, value2, "modifydate");
            return this;
        }

        public Criteria andModifyuseridIsNull() {
            addCriterion("MODIFYUSERID is null");
            return this;
        }

        public Criteria andModifyuseridIsNotNull() {
            addCriterion("MODIFYUSERID is not null");
            return this;
        }

        public Criteria andModifyuseridEqualTo(String value) {
            addCriterion("MODIFYUSERID =", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridNotEqualTo(String value) {
            addCriterion("MODIFYUSERID <>", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridGreaterThan(String value) {
            addCriterion("MODIFYUSERID >", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYUSERID >=", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridLessThan(String value) {
            addCriterion("MODIFYUSERID <", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridLessThanOrEqualTo(String value) {
            addCriterion("MODIFYUSERID <=", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridLike(String value) {
            addCriterion("MODIFYUSERID like", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridNotLike(String value) {
            addCriterion("MODIFYUSERID not like", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridIn(List values) {
            addCriterion("MODIFYUSERID in", values, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridNotIn(List values) {
            addCriterion("MODIFYUSERID not in", values, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridBetween(String value1, String value2) {
            addCriterion("MODIFYUSERID between", value1, value2, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridNotBetween(String value1, String value2) {
            addCriterion("MODIFYUSERID not between", value1, value2, "modifyuserid");
            return this;
        }

        public Criteria andModifyuserrealnameIsNull() {
            addCriterion("MODIFYUSERREALNAME is null");
            return this;
        }

        public Criteria andModifyuserrealnameIsNotNull() {
            addCriterion("MODIFYUSERREALNAME is not null");
            return this;
        }

        public Criteria andModifyuserrealnameEqualTo(String value) {
            addCriterion("MODIFYUSERREALNAME =", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameNotEqualTo(String value) {
            addCriterion("MODIFYUSERREALNAME <>", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameGreaterThan(String value) {
            addCriterion("MODIFYUSERREALNAME >", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYUSERREALNAME >=", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameLessThan(String value) {
            addCriterion("MODIFYUSERREALNAME <", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameLessThanOrEqualTo(String value) {
            addCriterion("MODIFYUSERREALNAME <=", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameLike(String value) {
            addCriterion("MODIFYUSERREALNAME like", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameNotLike(String value) {
            addCriterion("MODIFYUSERREALNAME not like", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameIn(List values) {
            addCriterion("MODIFYUSERREALNAME in", values, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameNotIn(List values) {
            addCriterion("MODIFYUSERREALNAME not in", values, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameBetween(String value1, String value2) {
            addCriterion("MODIFYUSERREALNAME between", value1, value2, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameNotBetween(String value1, String value2) {
            addCriterion("MODIFYUSERREALNAME not between", value1, value2, "modifyuserrealname");
            return this;
        }
    }
}