package com.gh.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BaseOperating {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_OPERATING.FUID
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	private String id;
	private String text;
	private Boolean checked;
	private Boolean hasChild;
	private String state;
	private String attributes;
	
	
	private String fuid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_OPERATING.MENUID
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	private String menuid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_OPERATING.CODE
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	private String code;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_OPERATING.DELETEMARK
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	private int deletemark;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_OPERATING.DESCRIPTION
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	private String description;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_OPERATING.CREATEDATE
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	private Date createdate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_OPERATING.CREATEUSERREALNAME
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	private String createuserrealname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_OPERATING.CREATEUSERID
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	private String createuserid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_OPERATING.MODIFYDATE
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	private Date modifydate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_OPERATING.MODIFYUSERREALNAME
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	private String modifyuserrealname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_OPERATING.MODIFYUSERID
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	private String modifyuserid;
	
	private String fullname;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_OPERATING.FUID
	 * @return  the value of GHPORT.BASE_OPERATING.FUID
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public String getFuid() {
		return fuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_OPERATING.FUID
	 * @param fuid  the value for GHPORT.BASE_OPERATING.FUID
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public void setFuid(String fuid) {
		this.fuid = fuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_OPERATING.MENUID
	 * @return  the value of GHPORT.BASE_OPERATING.MENUID
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public String getMenuid() {
		return menuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_OPERATING.MENUID
	 * @param menuid  the value for GHPORT.BASE_OPERATING.MENUID
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public void setMenuid(String menuid) {
		this.menuid = menuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_OPERATING.CODE
	 * @return  the value of GHPORT.BASE_OPERATING.CODE
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_OPERATING.CODE
	 * @param code  the value for GHPORT.BASE_OPERATING.CODE
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_OPERATING.DELETEMARK
	 * @return  the value of GHPORT.BASE_OPERATING.DELETEMARK
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_OPERATING.DESCRIPTION
	 * @param description  the value for GHPORT.BASE_OPERATING.DESCRIPTION
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_OPERATING.CREATEDATE
	 * @return  the value of GHPORT.BASE_OPERATING.CREATEDATE
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_OPERATING.CREATEDATE
	 * @param createdate  the value for GHPORT.BASE_OPERATING.CREATEDATE
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_OPERATING.CREATEUSERREALNAME
	 * @return  the value of GHPORT.BASE_OPERATING.CREATEUSERREALNAME
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public String getCreateuserrealname() {
		return createuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_OPERATING.CREATEUSERREALNAME
	 * @param createuserrealname  the value for GHPORT.BASE_OPERATING.CREATEUSERREALNAME
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public void setCreateuserrealname(String createuserrealname) {
		this.createuserrealname = createuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_OPERATING.CREATEUSERID
	 * @return  the value of GHPORT.BASE_OPERATING.CREATEUSERID
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public String getCreateuserid() {
		return createuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_OPERATING.CREATEUSERID
	 * @param createuserid  the value for GHPORT.BASE_OPERATING.CREATEUSERID
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_OPERATING.MODIFYDATE
	 * @return  the value of GHPORT.BASE_OPERATING.MODIFYDATE
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_OPERATING.MODIFYDATE
	 * @param modifydate  the value for GHPORT.BASE_OPERATING.MODIFYDATE
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_OPERATING.MODIFYUSERREALNAME
	 * @return  the value of GHPORT.BASE_OPERATING.MODIFYUSERREALNAME
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public String getModifyuserrealname() {
		return modifyuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_OPERATING.MODIFYUSERREALNAME
	 * @param modifyuserrealname  the value for GHPORT.BASE_OPERATING.MODIFYUSERREALNAME
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public void setModifyuserrealname(String modifyuserrealname) {
		this.modifyuserrealname = modifyuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_OPERATING.MODIFYUSERID
	 * @return  the value of GHPORT.BASE_OPERATING.MODIFYUSERID
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public String getModifyuserid() {
		return modifyuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_OPERATING.MODIFYUSERID
	 * @param modifyuserid  the value for GHPORT.BASE_OPERATING.MODIFYUSERID
	 * @abatorgenerated  Tue Mar 26 10:28:07 CST 2013
	 */
	public void setModifyuserid(String modifyuserid) {
		this.modifyuserid = modifyuserid;
	}

	public int getDeletemark() {
		return deletemark;
	}

	public void setDeletemark(int deletemark) {
		this.deletemark = deletemark;
	}

	public String getFullname() {
		return fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Boolean getChecked() {
		return checked;
	}

	public void setChecked(Boolean checked) {
		this.checked = checked;
	}

	public Boolean getHasChild() {
		return hasChild;
	}

	public void setHasChild(Boolean hasChild) {
		this.hasChild = hasChild;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getAttributes() {
		return attributes;
	}

	public void setAttributes(String attributes) {
		this.attributes = attributes;
	}


}