package com.gh.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class BaseScopeExample {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table GHPORT.BASE_SCOPE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database table GHPORT.BASE_SCOPE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    protected List oredCriteria;

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_SCOPE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public BaseScopeExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_SCOPE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    protected BaseScopeExample(BaseScopeExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_SCOPE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_SCOPE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_SCOPE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_SCOPE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_SCOPE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_SCOPE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table GHPORT.BASE_SCOPE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table GHPORT.BASE_SCOPE
     *
     * @abatorgenerated Wed Mar 20 21:05:45 CST 2013
     */
    public static class Criteria {
        protected List criteriaWithoutValue;

        protected List criteriaWithSingleValue;

        protected List criteriaWithListValue;

        protected List criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList();
            criteriaWithSingleValue = new ArrayList();
            criteriaWithListValue = new ArrayList();
            criteriaWithBetweenValue = new ArrayList();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List list = new ArrayList();
            list.add(value1);
            list.add(value2);
            Map map = new HashMap();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(((Date)iter.next()).getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andFuidIsNull() {
            addCriterion("FUID is null");
            return this;
        }

        public Criteria andFuidIsNotNull() {
            addCriterion("FUID is not null");
            return this;
        }

        public Criteria andFuidEqualTo(String value) {
            addCriterion("FUID =", value, "fuid");
            return this;
        }

        public Criteria andFuidNotEqualTo(String value) {
            addCriterion("FUID <>", value, "fuid");
            return this;
        }

        public Criteria andFuidGreaterThan(String value) {
            addCriterion("FUID >", value, "fuid");
            return this;
        }

        public Criteria andFuidGreaterThanOrEqualTo(String value) {
            addCriterion("FUID >=", value, "fuid");
            return this;
        }

        public Criteria andFuidLessThan(String value) {
            addCriterion("FUID <", value, "fuid");
            return this;
        }

        public Criteria andFuidLessThanOrEqualTo(String value) {
            addCriterion("FUID <=", value, "fuid");
            return this;
        }

        public Criteria andFuidLike(String value) {
            addCriterion("FUID like", value, "fuid");
            return this;
        }

        public Criteria andFuidNotLike(String value) {
            addCriterion("FUID not like", value, "fuid");
            return this;
        }

        public Criteria andFuidIn(List values) {
            addCriterion("FUID in", values, "fuid");
            return this;
        }

        public Criteria andFuidNotIn(List values) {
            addCriterion("FUID not in", values, "fuid");
            return this;
        }

        public Criteria andFuidBetween(String value1, String value2) {
            addCriterion("FUID between", value1, value2, "fuid");
            return this;
        }

        public Criteria andFuidNotBetween(String value1, String value2) {
            addCriterion("FUID not between", value1, value2, "fuid");
            return this;
        }

        public Criteria andMenuIdIsNull() {
            addCriterion("MENU_ID is null");
            return this;
        }

        public Criteria andMenuIdIsNotNull() {
            addCriterion("MENU_ID is not null");
            return this;
        }

        public Criteria andMenuIdEqualTo(String value) {
            addCriterion("MENU_ID =", value, "menuId");
            return this;
        }

        public Criteria andMenuIdNotEqualTo(String value) {
            addCriterion("MENU_ID <>", value, "menuId");
            return this;
        }

        public Criteria andMenuIdGreaterThan(String value) {
            addCriterion("MENU_ID >", value, "menuId");
            return this;
        }

        public Criteria andMenuIdGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_ID >=", value, "menuId");
            return this;
        }

        public Criteria andMenuIdLessThan(String value) {
            addCriterion("MENU_ID <", value, "menuId");
            return this;
        }

        public Criteria andMenuIdLessThanOrEqualTo(String value) {
            addCriterion("MENU_ID <=", value, "menuId");
            return this;
        }

        public Criteria andMenuIdLike(String value) {
            addCriterion("MENU_ID like", value, "menuId");
            return this;
        }

        public Criteria andMenuIdNotLike(String value) {
            addCriterion("MENU_ID not like", value, "menuId");
            return this;
        }

        public Criteria andMenuIdIn(List values) {
            addCriterion("MENU_ID in", values, "menuId");
            return this;
        }

        public Criteria andMenuIdNotIn(List values) {
            addCriterion("MENU_ID not in", values, "menuId");
            return this;
        }

        public Criteria andMenuIdBetween(String value1, String value2) {
            addCriterion("MENU_ID between", value1, value2, "menuId");
            return this;
        }

        public Criteria andMenuIdNotBetween(String value1, String value2) {
            addCriterion("MENU_ID not between", value1, value2, "menuId");
            return this;
        }

        public Criteria andRoleIdIsNull() {
            addCriterion("ROLE_ID is null");
            return this;
        }

        public Criteria andRoleIdIsNotNull() {
            addCriterion("ROLE_ID is not null");
            return this;
        }

        public Criteria andRoleIdEqualTo(String value) {
            addCriterion("ROLE_ID =", value, "roleId");
            return this;
        }

        public Criteria andRoleIdNotEqualTo(String value) {
            addCriterion("ROLE_ID <>", value, "roleId");
            return this;
        }

        public Criteria andRoleIdGreaterThan(String value) {
            addCriterion("ROLE_ID >", value, "roleId");
            return this;
        }

        public Criteria andRoleIdGreaterThanOrEqualTo(String value) {
            addCriterion("ROLE_ID >=", value, "roleId");
            return this;
        }

        public Criteria andRoleIdLessThan(String value) {
            addCriterion("ROLE_ID <", value, "roleId");
            return this;
        }

        public Criteria andRoleIdLessThanOrEqualTo(String value) {
            addCriterion("ROLE_ID <=", value, "roleId");
            return this;
        }

        public Criteria andRoleIdLike(String value) {
            addCriterion("ROLE_ID like", value, "roleId");
            return this;
        }

        public Criteria andRoleIdNotLike(String value) {
            addCriterion("ROLE_ID not like", value, "roleId");
            return this;
        }

        public Criteria andRoleIdIn(List values) {
            addCriterion("ROLE_ID in", values, "roleId");
            return this;
        }

        public Criteria andRoleIdNotIn(List values) {
            addCriterion("ROLE_ID not in", values, "roleId");
            return this;
        }

        public Criteria andRoleIdBetween(String value1, String value2) {
            addCriterion("ROLE_ID between", value1, value2, "roleId");
            return this;
        }

        public Criteria andRoleIdNotBetween(String value1, String value2) {
            addCriterion("ROLE_ID not between", value1, value2, "roleId");
            return this;
        }

        public Criteria andOrganizeIdIsNull() {
            addCriterion("ORGANIZE_ID is null");
            return this;
        }

        public Criteria andOrganizeIdIsNotNull() {
            addCriterion("ORGANIZE_ID is not null");
            return this;
        }

        public Criteria andOrganizeIdEqualTo(String value) {
            addCriterion("ORGANIZE_ID =", value, "organizeId");
            return this;
        }

        public Criteria andOrganizeIdNotEqualTo(String value) {
            addCriterion("ORGANIZE_ID <>", value, "organizeId");
            return this;
        }

        public Criteria andOrganizeIdGreaterThan(String value) {
            addCriterion("ORGANIZE_ID >", value, "organizeId");
            return this;
        }

        public Criteria andOrganizeIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANIZE_ID >=", value, "organizeId");
            return this;
        }

        public Criteria andOrganizeIdLessThan(String value) {
            addCriterion("ORGANIZE_ID <", value, "organizeId");
            return this;
        }

        public Criteria andOrganizeIdLessThanOrEqualTo(String value) {
            addCriterion("ORGANIZE_ID <=", value, "organizeId");
            return this;
        }

        public Criteria andOrganizeIdLike(String value) {
            addCriterion("ORGANIZE_ID like", value, "organizeId");
            return this;
        }

        public Criteria andOrganizeIdNotLike(String value) {
            addCriterion("ORGANIZE_ID not like", value, "organizeId");
            return this;
        }

        public Criteria andOrganizeIdIn(List values) {
            addCriterion("ORGANIZE_ID in", values, "organizeId");
            return this;
        }

        public Criteria andOrganizeIdNotIn(List values) {
            addCriterion("ORGANIZE_ID not in", values, "organizeId");
            return this;
        }

        public Criteria andOrganizeIdBetween(String value1, String value2) {
            addCriterion("ORGANIZE_ID between", value1, value2, "organizeId");
            return this;
        }

        public Criteria andOrganizeIdNotBetween(String value1, String value2) {
            addCriterion("ORGANIZE_ID not between", value1, value2, "organizeId");
            return this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("ENABLED is null");
            return this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("ENABLED is not null");
            return this;
        }

        public Criteria andEnabledEqualTo(BigDecimal value) {
            addCriterion("ENABLED =", value, "enabled");
            return this;
        }

        public Criteria andEnabledNotEqualTo(BigDecimal value) {
            addCriterion("ENABLED <>", value, "enabled");
            return this;
        }

        public Criteria andEnabledGreaterThan(BigDecimal value) {
            addCriterion("ENABLED >", value, "enabled");
            return this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ENABLED >=", value, "enabled");
            return this;
        }

        public Criteria andEnabledLessThan(BigDecimal value) {
            addCriterion("ENABLED <", value, "enabled");
            return this;
        }

        public Criteria andEnabledLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ENABLED <=", value, "enabled");
            return this;
        }

        public Criteria andEnabledIn(List values) {
            addCriterion("ENABLED in", values, "enabled");
            return this;
        }

        public Criteria andEnabledNotIn(List values) {
            addCriterion("ENABLED not in", values, "enabled");
            return this;
        }

        public Criteria andEnabledBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ENABLED between", value1, value2, "enabled");
            return this;
        }

        public Criteria andEnabledNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ENABLED not between", value1, value2, "enabled");
            return this;
        }

        public Criteria andDeletemarkIsNull() {
            addCriterion("DELETEMARK is null");
            return this;
        }

        public Criteria andDeletemarkIsNotNull() {
            addCriterion("DELETEMARK is not null");
            return this;
        }

        public Criteria andDeletemarkEqualTo(BigDecimal value) {
            addCriterion("DELETEMARK =", value, "deletemark");
            return this;
        }

        public Criteria andDeletemarkNotEqualTo(BigDecimal value) {
            addCriterion("DELETEMARK <>", value, "deletemark");
            return this;
        }

        public Criteria andDeletemarkGreaterThan(BigDecimal value) {
            addCriterion("DELETEMARK >", value, "deletemark");
            return this;
        }

        public Criteria andDeletemarkGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DELETEMARK >=", value, "deletemark");
            return this;
        }

        public Criteria andDeletemarkLessThan(BigDecimal value) {
            addCriterion("DELETEMARK <", value, "deletemark");
            return this;
        }

        public Criteria andDeletemarkLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DELETEMARK <=", value, "deletemark");
            return this;
        }

        public Criteria andDeletemarkIn(List values) {
            addCriterion("DELETEMARK in", values, "deletemark");
            return this;
        }

        public Criteria andDeletemarkNotIn(List values) {
            addCriterion("DELETEMARK not in", values, "deletemark");
            return this;
        }

        public Criteria andDeletemarkBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DELETEMARK between", value1, value2, "deletemark");
            return this;
        }

        public Criteria andDeletemarkNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DELETEMARK not between", value1, value2, "deletemark");
            return this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return this;
        }

        public Criteria andDescriptionIn(List values) {
            addCriterion("DESCRIPTION in", values, "description");
            return this;
        }

        public Criteria andDescriptionNotIn(List values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE =", value, "createdate");
            return this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE <>", value, "createdate");
            return this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterionForJDBCDate("CREATEDATE >", value, "createdate");
            return this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE >=", value, "createdate");
            return this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterionForJDBCDate("CREATEDATE <", value, "createdate");
            return this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("CREATEDATE <=", value, "createdate");
            return this;
        }

        public Criteria andCreatedateIn(List values) {
            addCriterionForJDBCDate("CREATEDATE in", values, "createdate");
            return this;
        }

        public Criteria andCreatedateNotIn(List values) {
            addCriterionForJDBCDate("CREATEDATE not in", values, "createdate");
            return this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATEDATE between", value1, value2, "createdate");
            return this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("CREATEDATE not between", value1, value2, "createdate");
            return this;
        }

        public Criteria andCreateuserrealnameIsNull() {
            addCriterion("CREATEUSERREALNAME is null");
            return this;
        }

        public Criteria andCreateuserrealnameIsNotNull() {
            addCriterion("CREATEUSERREALNAME is not null");
            return this;
        }

        public Criteria andCreateuserrealnameEqualTo(String value) {
            addCriterion("CREATEUSERREALNAME =", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameNotEqualTo(String value) {
            addCriterion("CREATEUSERREALNAME <>", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameGreaterThan(String value) {
            addCriterion("CREATEUSERREALNAME >", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSERREALNAME >=", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameLessThan(String value) {
            addCriterion("CREATEUSERREALNAME <", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSERREALNAME <=", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameLike(String value) {
            addCriterion("CREATEUSERREALNAME like", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameNotLike(String value) {
            addCriterion("CREATEUSERREALNAME not like", value, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameIn(List values) {
            addCriterion("CREATEUSERREALNAME in", values, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameNotIn(List values) {
            addCriterion("CREATEUSERREALNAME not in", values, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameBetween(String value1, String value2) {
            addCriterion("CREATEUSERREALNAME between", value1, value2, "createuserrealname");
            return this;
        }

        public Criteria andCreateuserrealnameNotBetween(String value1, String value2) {
            addCriterion("CREATEUSERREALNAME not between", value1, value2, "createuserrealname");
            return this;
        }

        public Criteria andCreateuseridIsNull() {
            addCriterion("CREATEUSERID is null");
            return this;
        }

        public Criteria andCreateuseridIsNotNull() {
            addCriterion("CREATEUSERID is not null");
            return this;
        }

        public Criteria andCreateuseridEqualTo(String value) {
            addCriterion("CREATEUSERID =", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridNotEqualTo(String value) {
            addCriterion("CREATEUSERID <>", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridGreaterThan(String value) {
            addCriterion("CREATEUSERID >", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridGreaterThanOrEqualTo(String value) {
            addCriterion("CREATEUSERID >=", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridLessThan(String value) {
            addCriterion("CREATEUSERID <", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridLessThanOrEqualTo(String value) {
            addCriterion("CREATEUSERID <=", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridLike(String value) {
            addCriterion("CREATEUSERID like", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridNotLike(String value) {
            addCriterion("CREATEUSERID not like", value, "createuserid");
            return this;
        }

        public Criteria andCreateuseridIn(List values) {
            addCriterion("CREATEUSERID in", values, "createuserid");
            return this;
        }

        public Criteria andCreateuseridNotIn(List values) {
            addCriterion("CREATEUSERID not in", values, "createuserid");
            return this;
        }

        public Criteria andCreateuseridBetween(String value1, String value2) {
            addCriterion("CREATEUSERID between", value1, value2, "createuserid");
            return this;
        }

        public Criteria andCreateuseridNotBetween(String value1, String value2) {
            addCriterion("CREATEUSERID not between", value1, value2, "createuserid");
            return this;
        }

        public Criteria andModifydateIsNull() {
            addCriterion("MODIFYDATE is null");
            return this;
        }

        public Criteria andModifydateIsNotNull() {
            addCriterion("MODIFYDATE is not null");
            return this;
        }

        public Criteria andModifydateEqualTo(Date value) {
            addCriterionForJDBCDate("MODIFYDATE =", value, "modifydate");
            return this;
        }

        public Criteria andModifydateNotEqualTo(Date value) {
            addCriterionForJDBCDate("MODIFYDATE <>", value, "modifydate");
            return this;
        }

        public Criteria andModifydateGreaterThan(Date value) {
            addCriterionForJDBCDate("MODIFYDATE >", value, "modifydate");
            return this;
        }

        public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MODIFYDATE >=", value, "modifydate");
            return this;
        }

        public Criteria andModifydateLessThan(Date value) {
            addCriterionForJDBCDate("MODIFYDATE <", value, "modifydate");
            return this;
        }

        public Criteria andModifydateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("MODIFYDATE <=", value, "modifydate");
            return this;
        }

        public Criteria andModifydateIn(List values) {
            addCriterionForJDBCDate("MODIFYDATE in", values, "modifydate");
            return this;
        }

        public Criteria andModifydateNotIn(List values) {
            addCriterionForJDBCDate("MODIFYDATE not in", values, "modifydate");
            return this;
        }

        public Criteria andModifydateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MODIFYDATE between", value1, value2, "modifydate");
            return this;
        }

        public Criteria andModifydateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("MODIFYDATE not between", value1, value2, "modifydate");
            return this;
        }

        public Criteria andModifyuserrealnameIsNull() {
            addCriterion("MODIFYUSERREALNAME is null");
            return this;
        }

        public Criteria andModifyuserrealnameIsNotNull() {
            addCriterion("MODIFYUSERREALNAME is not null");
            return this;
        }

        public Criteria andModifyuserrealnameEqualTo(String value) {
            addCriterion("MODIFYUSERREALNAME =", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameNotEqualTo(String value) {
            addCriterion("MODIFYUSERREALNAME <>", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameGreaterThan(String value) {
            addCriterion("MODIFYUSERREALNAME >", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYUSERREALNAME >=", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameLessThan(String value) {
            addCriterion("MODIFYUSERREALNAME <", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameLessThanOrEqualTo(String value) {
            addCriterion("MODIFYUSERREALNAME <=", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameLike(String value) {
            addCriterion("MODIFYUSERREALNAME like", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameNotLike(String value) {
            addCriterion("MODIFYUSERREALNAME not like", value, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameIn(List values) {
            addCriterion("MODIFYUSERREALNAME in", values, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameNotIn(List values) {
            addCriterion("MODIFYUSERREALNAME not in", values, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameBetween(String value1, String value2) {
            addCriterion("MODIFYUSERREALNAME between", value1, value2, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuserrealnameNotBetween(String value1, String value2) {
            addCriterion("MODIFYUSERREALNAME not between", value1, value2, "modifyuserrealname");
            return this;
        }

        public Criteria andModifyuseridIsNull() {
            addCriterion("MODIFYUSERID is null");
            return this;
        }

        public Criteria andModifyuseridIsNotNull() {
            addCriterion("MODIFYUSERID is not null");
            return this;
        }

        public Criteria andModifyuseridEqualTo(String value) {
            addCriterion("MODIFYUSERID =", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridNotEqualTo(String value) {
            addCriterion("MODIFYUSERID <>", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridGreaterThan(String value) {
            addCriterion("MODIFYUSERID >", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFYUSERID >=", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridLessThan(String value) {
            addCriterion("MODIFYUSERID <", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridLessThanOrEqualTo(String value) {
            addCriterion("MODIFYUSERID <=", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridLike(String value) {
            addCriterion("MODIFYUSERID like", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridNotLike(String value) {
            addCriterion("MODIFYUSERID not like", value, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridIn(List values) {
            addCriterion("MODIFYUSERID in", values, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridNotIn(List values) {
            addCriterion("MODIFYUSERID not in", values, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridBetween(String value1, String value2) {
            addCriterion("MODIFYUSERID between", value1, value2, "modifyuserid");
            return this;
        }

        public Criteria andModifyuseridNotBetween(String value1, String value2) {
            addCriterion("MODIFYUSERID not between", value1, value2, "modifyuserid");
            return this;
        }
    }
}