package com.gh.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class BaseMenuExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table base_menu
	 * @abatorgenerated  Sun Apr 13 14:17:11 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table base_menu
	 * @abatorgenerated  Sun Apr 13 14:17:11 CST 2014
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table base_menu
	 * @abatorgenerated  Sun Apr 13 14:17:11 CST 2014
	 */
	public BaseMenuExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table base_menu
	 * @abatorgenerated  Sun Apr 13 14:17:11 CST 2014
	 */
	protected BaseMenuExample(BaseMenuExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table base_menu
	 * @abatorgenerated  Sun Apr 13 14:17:11 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table base_menu
	 * @abatorgenerated  Sun Apr 13 14:17:11 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table base_menu
	 * @abatorgenerated  Sun Apr 13 14:17:11 CST 2014
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table base_menu
	 * @abatorgenerated  Sun Apr 13 14:17:11 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table base_menu
	 * @abatorgenerated  Sun Apr 13 14:17:11 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table base_menu
	 * @abatorgenerated  Sun Apr 13 14:17:11 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table base_menu
	 * @abatorgenerated  Sun Apr 13 14:17:11 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table base_menu
	 * @abatorgenerated  Sun Apr 13 14:17:11 CST 2014
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andFuidIsNull() {
			addCriterion("FUID is null");
			return this;
		}

		public Criteria andFuidIsNotNull() {
			addCriterion("FUID is not null");
			return this;
		}

		public Criteria andFuidEqualTo(String value) {
			addCriterion("FUID =", value, "fuid");
			return this;
		}

		public Criteria andFuidNotEqualTo(String value) {
			addCriterion("FUID <>", value, "fuid");
			return this;
		}

		public Criteria andFuidGreaterThan(String value) {
			addCriterion("FUID >", value, "fuid");
			return this;
		}

		public Criteria andFuidGreaterThanOrEqualTo(String value) {
			addCriterion("FUID >=", value, "fuid");
			return this;
		}

		public Criteria andFuidLessThan(String value) {
			addCriterion("FUID <", value, "fuid");
			return this;
		}

		public Criteria andFuidLessThanOrEqualTo(String value) {
			addCriterion("FUID <=", value, "fuid");
			return this;
		}

		public Criteria andFuidLike(String value) {
			addCriterion("FUID like", value, "fuid");
			return this;
		}

		public Criteria andFuidNotLike(String value) {
			addCriterion("FUID not like", value, "fuid");
			return this;
		}

		public Criteria andFuidIn(List values) {
			addCriterion("FUID in", values, "fuid");
			return this;
		}

		public Criteria andFuidNotIn(List values) {
			addCriterion("FUID not in", values, "fuid");
			return this;
		}

		public Criteria andFuidBetween(String value1, String value2) {
			addCriterion("FUID between", value1, value2, "fuid");
			return this;
		}

		public Criteria andFuidNotBetween(String value1, String value2) {
			addCriterion("FUID not between", value1, value2, "fuid");
			return this;
		}

		public Criteria andMenuNameIsNull() {
			addCriterion("MENU_NAME is null");
			return this;
		}

		public Criteria andMenuNameIsNotNull() {
			addCriterion("MENU_NAME is not null");
			return this;
		}

		public Criteria andMenuNameEqualTo(String value) {
			addCriterion("MENU_NAME =", value, "menuName");
			return this;
		}

		public Criteria andMenuNameNotEqualTo(String value) {
			addCriterion("MENU_NAME <>", value, "menuName");
			return this;
		}

		public Criteria andMenuNameGreaterThan(String value) {
			addCriterion("MENU_NAME >", value, "menuName");
			return this;
		}

		public Criteria andMenuNameGreaterThanOrEqualTo(String value) {
			addCriterion("MENU_NAME >=", value, "menuName");
			return this;
		}

		public Criteria andMenuNameLessThan(String value) {
			addCriterion("MENU_NAME <", value, "menuName");
			return this;
		}

		public Criteria andMenuNameLessThanOrEqualTo(String value) {
			addCriterion("MENU_NAME <=", value, "menuName");
			return this;
		}

		public Criteria andMenuNameLike(String value) {
			addCriterion("MENU_NAME like", value, "menuName");
			return this;
		}

		public Criteria andMenuNameNotLike(String value) {
			addCriterion("MENU_NAME not like", value, "menuName");
			return this;
		}

		public Criteria andMenuNameIn(List values) {
			addCriterion("MENU_NAME in", values, "menuName");
			return this;
		}

		public Criteria andMenuNameNotIn(List values) {
			addCriterion("MENU_NAME not in", values, "menuName");
			return this;
		}

		public Criteria andMenuNameBetween(String value1, String value2) {
			addCriterion("MENU_NAME between", value1, value2, "menuName");
			return this;
		}

		public Criteria andMenuNameNotBetween(String value1, String value2) {
			addCriterion("MENU_NAME not between", value1, value2, "menuName");
			return this;
		}

		public Criteria andMenuParentidIsNull() {
			addCriterion("MENU_PARENTID is null");
			return this;
		}

		public Criteria andMenuParentidIsNotNull() {
			addCriterion("MENU_PARENTID is not null");
			return this;
		}

		public Criteria andMenuParentidEqualTo(String value) {
			addCriterion("MENU_PARENTID =", value, "menuParentid");
			return this;
		}

		public Criteria andMenuParentidNotEqualTo(String value) {
			addCriterion("MENU_PARENTID <>", value, "menuParentid");
			return this;
		}

		public Criteria andMenuParentidGreaterThan(String value) {
			addCriterion("MENU_PARENTID >", value, "menuParentid");
			return this;
		}

		public Criteria andMenuParentidGreaterThanOrEqualTo(String value) {
			addCriterion("MENU_PARENTID >=", value, "menuParentid");
			return this;
		}

		public Criteria andMenuParentidLessThan(String value) {
			addCriterion("MENU_PARENTID <", value, "menuParentid");
			return this;
		}

		public Criteria andMenuParentidLessThanOrEqualTo(String value) {
			addCriterion("MENU_PARENTID <=", value, "menuParentid");
			return this;
		}

		public Criteria andMenuParentidLike(String value) {
			addCriterion("MENU_PARENTID like", value, "menuParentid");
			return this;
		}

		public Criteria andMenuParentidNotLike(String value) {
			addCriterion("MENU_PARENTID not like", value, "menuParentid");
			return this;
		}

		public Criteria andMenuParentidIn(List values) {
			addCriterion("MENU_PARENTID in", values, "menuParentid");
			return this;
		}

		public Criteria andMenuParentidNotIn(List values) {
			addCriterion("MENU_PARENTID not in", values, "menuParentid");
			return this;
		}

		public Criteria andMenuParentidBetween(String value1, String value2) {
			addCriterion("MENU_PARENTID between", value1, value2, "menuParentid");
			return this;
		}

		public Criteria andMenuParentidNotBetween(String value1, String value2) {
			addCriterion("MENU_PARENTID not between", value1, value2, "menuParentid");
			return this;
		}

		public Criteria andMenuUrlIsNull() {
			addCriterion("MENU_URL is null");
			return this;
		}

		public Criteria andMenuUrlIsNotNull() {
			addCriterion("MENU_URL is not null");
			return this;
		}

		public Criteria andMenuUrlEqualTo(String value) {
			addCriterion("MENU_URL =", value, "menuUrl");
			return this;
		}

		public Criteria andMenuUrlNotEqualTo(String value) {
			addCriterion("MENU_URL <>", value, "menuUrl");
			return this;
		}

		public Criteria andMenuUrlGreaterThan(String value) {
			addCriterion("MENU_URL >", value, "menuUrl");
			return this;
		}

		public Criteria andMenuUrlGreaterThanOrEqualTo(String value) {
			addCriterion("MENU_URL >=", value, "menuUrl");
			return this;
		}

		public Criteria andMenuUrlLessThan(String value) {
			addCriterion("MENU_URL <", value, "menuUrl");
			return this;
		}

		public Criteria andMenuUrlLessThanOrEqualTo(String value) {
			addCriterion("MENU_URL <=", value, "menuUrl");
			return this;
		}

		public Criteria andMenuUrlLike(String value) {
			addCriterion("MENU_URL like", value, "menuUrl");
			return this;
		}

		public Criteria andMenuUrlNotLike(String value) {
			addCriterion("MENU_URL not like", value, "menuUrl");
			return this;
		}

		public Criteria andMenuUrlIn(List values) {
			addCriterion("MENU_URL in", values, "menuUrl");
			return this;
		}

		public Criteria andMenuUrlNotIn(List values) {
			addCriterion("MENU_URL not in", values, "menuUrl");
			return this;
		}

		public Criteria andMenuUrlBetween(String value1, String value2) {
			addCriterion("MENU_URL between", value1, value2, "menuUrl");
			return this;
		}

		public Criteria andMenuUrlNotBetween(String value1, String value2) {
			addCriterion("MENU_URL not between", value1, value2, "menuUrl");
			return this;
		}

		public Criteria andMenuOrderIsNull() {
			addCriterion("MENU_ORDER is null");
			return this;
		}

		public Criteria andMenuOrderIsNotNull() {
			addCriterion("MENU_ORDER is not null");
			return this;
		}

		public Criteria andMenuOrderEqualTo(Double value) {
			addCriterion("MENU_ORDER =", value, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderNotEqualTo(Double value) {
			addCriterion("MENU_ORDER <>", value, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderGreaterThan(Double value) {
			addCriterion("MENU_ORDER >", value, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderGreaterThanOrEqualTo(Double value) {
			addCriterion("MENU_ORDER >=", value, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderLessThan(Double value) {
			addCriterion("MENU_ORDER <", value, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderLessThanOrEqualTo(Double value) {
			addCriterion("MENU_ORDER <=", value, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderIn(List values) {
			addCriterion("MENU_ORDER in", values, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderNotIn(List values) {
			addCriterion("MENU_ORDER not in", values, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderBetween(Double value1, Double value2) {
			addCriterion("MENU_ORDER between", value1, value2, "menuOrder");
			return this;
		}

		public Criteria andMenuOrderNotBetween(Double value1, Double value2) {
			addCriterion("MENU_ORDER not between", value1, value2, "menuOrder");
			return this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("CREATEDATE is null");
			return this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("CREATEDATE is not null");
			return this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterion("CREATEDATE =", value, "createdate");
			return this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterion("CREATEDATE <>", value, "createdate");
			return this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterion("CREATEDATE >", value, "createdate");
			return this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATEDATE >=", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterion("CREATEDATE <", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterion("CREATEDATE <=", value, "createdate");
			return this;
		}

		public Criteria andCreatedateIn(List values) {
			addCriterion("CREATEDATE in", values, "createdate");
			return this;
		}

		public Criteria andCreatedateNotIn(List values) {
			addCriterion("CREATEDATE not in", values, "createdate");
			return this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterion("CREATEDATE between", value1, value2, "createdate");
			return this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterion("CREATEDATE not between", value1, value2, "createdate");
			return this;
		}

		public Criteria andModifydateIsNull() {
			addCriterion("MODIFYDATE is null");
			return this;
		}

		public Criteria andModifydateIsNotNull() {
			addCriterion("MODIFYDATE is not null");
			return this;
		}

		public Criteria andModifydateEqualTo(Date value) {
			addCriterion("MODIFYDATE =", value, "modifydate");
			return this;
		}

		public Criteria andModifydateNotEqualTo(Date value) {
			addCriterion("MODIFYDATE <>", value, "modifydate");
			return this;
		}

		public Criteria andModifydateGreaterThan(Date value) {
			addCriterion("MODIFYDATE >", value, "modifydate");
			return this;
		}

		public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFYDATE >=", value, "modifydate");
			return this;
		}

		public Criteria andModifydateLessThan(Date value) {
			addCriterion("MODIFYDATE <", value, "modifydate");
			return this;
		}

		public Criteria andModifydateLessThanOrEqualTo(Date value) {
			addCriterion("MODIFYDATE <=", value, "modifydate");
			return this;
		}

		public Criteria andModifydateIn(List values) {
			addCriterion("MODIFYDATE in", values, "modifydate");
			return this;
		}

		public Criteria andModifydateNotIn(List values) {
			addCriterion("MODIFYDATE not in", values, "modifydate");
			return this;
		}

		public Criteria andModifydateBetween(Date value1, Date value2) {
			addCriterion("MODIFYDATE between", value1, value2, "modifydate");
			return this;
		}

		public Criteria andModifydateNotBetween(Date value1, Date value2) {
			addCriterion("MODIFYDATE not between", value1, value2, "modifydate");
			return this;
		}

		public Criteria andCreateuserrealnameIsNull() {
			addCriterion("CREATEUSERREALNAME is null");
			return this;
		}

		public Criteria andCreateuserrealnameIsNotNull() {
			addCriterion("CREATEUSERREALNAME is not null");
			return this;
		}

		public Criteria andCreateuserrealnameEqualTo(String value) {
			addCriterion("CREATEUSERREALNAME =", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameNotEqualTo(String value) {
			addCriterion("CREATEUSERREALNAME <>", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameGreaterThan(String value) {
			addCriterion("CREATEUSERREALNAME >", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameGreaterThanOrEqualTo(String value) {
			addCriterion("CREATEUSERREALNAME >=", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameLessThan(String value) {
			addCriterion("CREATEUSERREALNAME <", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameLessThanOrEqualTo(String value) {
			addCriterion("CREATEUSERREALNAME <=", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameLike(String value) {
			addCriterion("CREATEUSERREALNAME like", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameNotLike(String value) {
			addCriterion("CREATEUSERREALNAME not like", value, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameIn(List values) {
			addCriterion("CREATEUSERREALNAME in", values, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameNotIn(List values) {
			addCriterion("CREATEUSERREALNAME not in", values, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameBetween(String value1, String value2) {
			addCriterion("CREATEUSERREALNAME between", value1, value2, "createuserrealname");
			return this;
		}

		public Criteria andCreateuserrealnameNotBetween(String value1, String value2) {
			addCriterion("CREATEUSERREALNAME not between", value1, value2, "createuserrealname");
			return this;
		}

		public Criteria andCreateuseridIsNull() {
			addCriterion("CREATEUSERID is null");
			return this;
		}

		public Criteria andCreateuseridIsNotNull() {
			addCriterion("CREATEUSERID is not null");
			return this;
		}

		public Criteria andCreateuseridEqualTo(String value) {
			addCriterion("CREATEUSERID =", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridNotEqualTo(String value) {
			addCriterion("CREATEUSERID <>", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridGreaterThan(String value) {
			addCriterion("CREATEUSERID >", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridGreaterThanOrEqualTo(String value) {
			addCriterion("CREATEUSERID >=", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridLessThan(String value) {
			addCriterion("CREATEUSERID <", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridLessThanOrEqualTo(String value) {
			addCriterion("CREATEUSERID <=", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridLike(String value) {
			addCriterion("CREATEUSERID like", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridNotLike(String value) {
			addCriterion("CREATEUSERID not like", value, "createuserid");
			return this;
		}

		public Criteria andCreateuseridIn(List values) {
			addCriterion("CREATEUSERID in", values, "createuserid");
			return this;
		}

		public Criteria andCreateuseridNotIn(List values) {
			addCriterion("CREATEUSERID not in", values, "createuserid");
			return this;
		}

		public Criteria andCreateuseridBetween(String value1, String value2) {
			addCriterion("CREATEUSERID between", value1, value2, "createuserid");
			return this;
		}

		public Criteria andCreateuseridNotBetween(String value1, String value2) {
			addCriterion("CREATEUSERID not between", value1, value2, "createuserid");
			return this;
		}

		public Criteria andModifyuserrealnameIsNull() {
			addCriterion("MODIFYUSERREALNAME is null");
			return this;
		}

		public Criteria andModifyuserrealnameIsNotNull() {
			addCriterion("MODIFYUSERREALNAME is not null");
			return this;
		}

		public Criteria andModifyuserrealnameEqualTo(String value) {
			addCriterion("MODIFYUSERREALNAME =", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameNotEqualTo(String value) {
			addCriterion("MODIFYUSERREALNAME <>", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameGreaterThan(String value) {
			addCriterion("MODIFYUSERREALNAME >", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFYUSERREALNAME >=", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameLessThan(String value) {
			addCriterion("MODIFYUSERREALNAME <", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameLessThanOrEqualTo(String value) {
			addCriterion("MODIFYUSERREALNAME <=", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameLike(String value) {
			addCriterion("MODIFYUSERREALNAME like", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameNotLike(String value) {
			addCriterion("MODIFYUSERREALNAME not like", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameIn(List values) {
			addCriterion("MODIFYUSERREALNAME in", values, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameNotIn(List values) {
			addCriterion("MODIFYUSERREALNAME not in", values, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameBetween(String value1, String value2) {
			addCriterion("MODIFYUSERREALNAME between", value1, value2, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameNotBetween(String value1, String value2) {
			addCriterion("MODIFYUSERREALNAME not between", value1, value2, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuseridIsNull() {
			addCriterion("MODIFYUSERID is null");
			return this;
		}

		public Criteria andModifyuseridIsNotNull() {
			addCriterion("MODIFYUSERID is not null");
			return this;
		}

		public Criteria andModifyuseridEqualTo(String value) {
			addCriterion("MODIFYUSERID =", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridNotEqualTo(String value) {
			addCriterion("MODIFYUSERID <>", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridGreaterThan(String value) {
			addCriterion("MODIFYUSERID >", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFYUSERID >=", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridLessThan(String value) {
			addCriterion("MODIFYUSERID <", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridLessThanOrEqualTo(String value) {
			addCriterion("MODIFYUSERID <=", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridLike(String value) {
			addCriterion("MODIFYUSERID like", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridNotLike(String value) {
			addCriterion("MODIFYUSERID not like", value, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridIn(List values) {
			addCriterion("MODIFYUSERID in", values, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridNotIn(List values) {
			addCriterion("MODIFYUSERID not in", values, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridBetween(String value1, String value2) {
			addCriterion("MODIFYUSERID between", value1, value2, "modifyuserid");
			return this;
		}

		public Criteria andModifyuseridNotBetween(String value1, String value2) {
			addCriterion("MODIFYUSERID not between", value1, value2, "modifyuserid");
			return this;
		}

		public Criteria andImagesIsNull() {
			addCriterion("images is null");
			return this;
		}

		public Criteria andImagesIsNotNull() {
			addCriterion("images is not null");
			return this;
		}

		public Criteria andImagesEqualTo(String value) {
			addCriterion("images =", value, "images");
			return this;
		}

		public Criteria andImagesNotEqualTo(String value) {
			addCriterion("images <>", value, "images");
			return this;
		}

		public Criteria andImagesGreaterThan(String value) {
			addCriterion("images >", value, "images");
			return this;
		}

		public Criteria andImagesGreaterThanOrEqualTo(String value) {
			addCriterion("images >=", value, "images");
			return this;
		}

		public Criteria andImagesLessThan(String value) {
			addCriterion("images <", value, "images");
			return this;
		}

		public Criteria andImagesLessThanOrEqualTo(String value) {
			addCriterion("images <=", value, "images");
			return this;
		}

		public Criteria andImagesLike(String value) {
			addCriterion("images like", value, "images");
			return this;
		}

		public Criteria andImagesNotLike(String value) {
			addCriterion("images not like", value, "images");
			return this;
		}

		public Criteria andImagesIn(List values) {
			addCriterion("images in", values, "images");
			return this;
		}

		public Criteria andImagesNotIn(List values) {
			addCriterion("images not in", values, "images");
			return this;
		}

		public Criteria andImagesBetween(String value1, String value2) {
			addCriterion("images between", value1, value2, "images");
			return this;
		}

		public Criteria andImagesNotBetween(String value1, String value2) {
			addCriterion("images not between", value1, value2, "images");
			return this;
		}
	}
}