package com.gh.entity;

import java.util.Date;

public class BaseOrganizeMenu {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE_MENU.FUID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	private String fuid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE_MENU.MENU_ID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	private String menuId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE_MENU.CREATEDATE
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	private Date createdate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE_MENU.CREATEUSERREALNAME
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	private String createuserrealname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE_MENU.CREATEUSERID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	private String createuserid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE_MENU.MODIFYDATE
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	private Date modifydate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE_MENU.MODIFYUSERREALNAME
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	private String modifyuserrealname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE_MENU.MODIFYUSERID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	private String modifyuserid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE_MENU.ORGANIZE_ID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	private String organizeId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_ORGANIZE_MENU.OPERATIONID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	private String operationid;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE_MENU.FUID
	 * @return  the value of GHPORT.BASE_ORGANIZE_MENU.FUID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public String getFuid() {
		return fuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE_MENU.FUID
	 * @param fuid  the value for GHPORT.BASE_ORGANIZE_MENU.FUID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public void setFuid(String fuid) {
		this.fuid = fuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE_MENU.MENU_ID
	 * @return  the value of GHPORT.BASE_ORGANIZE_MENU.MENU_ID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public String getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE_MENU.MENU_ID
	 * @param menuId  the value for GHPORT.BASE_ORGANIZE_MENU.MENU_ID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE_MENU.CREATEDATE
	 * @return  the value of GHPORT.BASE_ORGANIZE_MENU.CREATEDATE
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE_MENU.CREATEDATE
	 * @param createdate  the value for GHPORT.BASE_ORGANIZE_MENU.CREATEDATE
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE_MENU.CREATEUSERREALNAME
	 * @return  the value of GHPORT.BASE_ORGANIZE_MENU.CREATEUSERREALNAME
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public String getCreateuserrealname() {
		return createuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE_MENU.CREATEUSERREALNAME
	 * @param createuserrealname  the value for GHPORT.BASE_ORGANIZE_MENU.CREATEUSERREALNAME
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public void setCreateuserrealname(String createuserrealname) {
		this.createuserrealname = createuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE_MENU.CREATEUSERID
	 * @return  the value of GHPORT.BASE_ORGANIZE_MENU.CREATEUSERID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public String getCreateuserid() {
		return createuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE_MENU.CREATEUSERID
	 * @param createuserid  the value for GHPORT.BASE_ORGANIZE_MENU.CREATEUSERID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE_MENU.MODIFYDATE
	 * @return  the value of GHPORT.BASE_ORGANIZE_MENU.MODIFYDATE
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE_MENU.MODIFYDATE
	 * @param modifydate  the value for GHPORT.BASE_ORGANIZE_MENU.MODIFYDATE
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE_MENU.MODIFYUSERREALNAME
	 * @return  the value of GHPORT.BASE_ORGANIZE_MENU.MODIFYUSERREALNAME
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public String getModifyuserrealname() {
		return modifyuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE_MENU.MODIFYUSERREALNAME
	 * @param modifyuserrealname  the value for GHPORT.BASE_ORGANIZE_MENU.MODIFYUSERREALNAME
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public void setModifyuserrealname(String modifyuserrealname) {
		this.modifyuserrealname = modifyuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE_MENU.MODIFYUSERID
	 * @return  the value of GHPORT.BASE_ORGANIZE_MENU.MODIFYUSERID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public String getModifyuserid() {
		return modifyuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE_MENU.MODIFYUSERID
	 * @param modifyuserid  the value for GHPORT.BASE_ORGANIZE_MENU.MODIFYUSERID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public void setModifyuserid(String modifyuserid) {
		this.modifyuserid = modifyuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE_MENU.ORGANIZE_ID
	 * @return  the value of GHPORT.BASE_ORGANIZE_MENU.ORGANIZE_ID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public String getOrganizeId() {
		return organizeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE_MENU.ORGANIZE_ID
	 * @param organizeId  the value for GHPORT.BASE_ORGANIZE_MENU.ORGANIZE_ID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public void setOrganizeId(String organizeId) {
		this.organizeId = organizeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_ORGANIZE_MENU.OPERATIONID
	 * @return  the value of GHPORT.BASE_ORGANIZE_MENU.OPERATIONID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public String getOperationid() {
		return operationid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_ORGANIZE_MENU.OPERATIONID
	 * @param operationid  the value for GHPORT.BASE_ORGANIZE_MENU.OPERATIONID
	 * @abatorgenerated  Mon Oct 21 10:38:34 CST 2013
	 */
	public void setOperationid(String operationid) {
		this.operationid = operationid;
	}
}