package com.gh.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BaseUserRole {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_USER_ROLE.FUID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	private String fuid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_USER_ROLE.USERID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	private String userid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_USER_ROLE.ROLEID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	private String roleid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_USER_ROLE.CREATEDATE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	private Date createdate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_USER_ROLE.CREATEUSERID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	private String createuserid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_USER_ROLE.CREATEUSERREALNAME
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	private String createuserrealname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_USER_ROLE.MODIFYDATE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	private Date modifydate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_USER_ROLE.MODIFYUSERID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	private String modifyuserid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_USER_ROLE.MODIFYUSERREALNAME
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	private String modifyuserrealname;
	
	private String realname;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_USER_ROLE.FUID
	 * @return  the value of GHPORT.BASE_USER_ROLE.FUID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public String getFuid() {
		return fuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_USER_ROLE.FUID
	 * @param fuid  the value for GHPORT.BASE_USER_ROLE.FUID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public void setFuid(String fuid) {
		this.fuid = fuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_USER_ROLE.USERID
	 * @return  the value of GHPORT.BASE_USER_ROLE.USERID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_USER_ROLE.USERID
	 * @param userid  the value for GHPORT.BASE_USER_ROLE.USERID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_USER_ROLE.ROLEID
	 * @return  the value of GHPORT.BASE_USER_ROLE.ROLEID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public String getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_USER_ROLE.ROLEID
	 * @param roleid  the value for GHPORT.BASE_USER_ROLE.ROLEID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_USER_ROLE.CREATEDATE
	 * @return  the value of GHPORT.BASE_USER_ROLE.CREATEDATE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_USER_ROLE.CREATEDATE
	 * @param createdate  the value for GHPORT.BASE_USER_ROLE.CREATEDATE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_USER_ROLE.CREATEUSERID
	 * @return  the value of GHPORT.BASE_USER_ROLE.CREATEUSERID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public String getCreateuserid() {
		return createuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_USER_ROLE.CREATEUSERID
	 * @param createuserid  the value for GHPORT.BASE_USER_ROLE.CREATEUSERID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_USER_ROLE.CREATEUSERREALNAME
	 * @return  the value of GHPORT.BASE_USER_ROLE.CREATEUSERREALNAME
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public String getCreateuserrealname() {
		return createuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_USER_ROLE.CREATEUSERREALNAME
	 * @param createuserrealname  the value for GHPORT.BASE_USER_ROLE.CREATEUSERREALNAME
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public void setCreateuserrealname(String createuserrealname) {
		this.createuserrealname = createuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_USER_ROLE.MODIFYDATE
	 * @return  the value of GHPORT.BASE_USER_ROLE.MODIFYDATE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_USER_ROLE.MODIFYDATE
	 * @param modifydate  the value for GHPORT.BASE_USER_ROLE.MODIFYDATE
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_USER_ROLE.MODIFYUSERID
	 * @return  the value of GHPORT.BASE_USER_ROLE.MODIFYUSERID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public String getModifyuserid() {
		return modifyuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_USER_ROLE.MODIFYUSERID
	 * @param modifyuserid  the value for GHPORT.BASE_USER_ROLE.MODIFYUSERID
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public void setModifyuserid(String modifyuserid) {
		this.modifyuserid = modifyuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_USER_ROLE.MODIFYUSERREALNAME
	 * @return  the value of GHPORT.BASE_USER_ROLE.MODIFYUSERREALNAME
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public String getModifyuserrealname() {
		return modifyuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_USER_ROLE.MODIFYUSERREALNAME
	 * @param modifyuserrealname  the value for GHPORT.BASE_USER_ROLE.MODIFYUSERREALNAME
	 * @abatorgenerated  Mon Mar 25 11:44:25 CST 2013
	 */
	public void setModifyuserrealname(String modifyuserrealname) {
		this.modifyuserrealname = modifyuserrealname;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}
}