package com.gh.entity;

import java.util.Date;

public class BaseMenuRole {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_MENU_ROLE.FUID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	private String fuid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_MENU_ROLE.ROLE_ID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	private String roleId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_MENU_ROLE.MENU_ID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	private String menuId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_MENU_ROLE.OPERATING_ID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	private String operatingId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_MENU_ROLE.CREATEDATE
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	private Date createdate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_MENU_ROLE.CREATEUSERREALNAME
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	private String createuserrealname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_MENU_ROLE.CREATEUSERID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	private String createuserid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_MENU_ROLE.MODIFYDATE
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	private Date modifydate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_MENU_ROLE.MODIFYUSERREALNAME
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	private String modifyuserrealname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.BASE_MENU_ROLE.MODIFYUSERID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	private String modifyuserid;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_MENU_ROLE.FUID
	 * @return  the value of GHPORT.BASE_MENU_ROLE.FUID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public String getFuid() {
		return fuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_MENU_ROLE.FUID
	 * @param fuid  the value for GHPORT.BASE_MENU_ROLE.FUID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public void setFuid(String fuid) {
		this.fuid = fuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_MENU_ROLE.ROLE_ID
	 * @return  the value of GHPORT.BASE_MENU_ROLE.ROLE_ID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_MENU_ROLE.ROLE_ID
	 * @param roleId  the value for GHPORT.BASE_MENU_ROLE.ROLE_ID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_MENU_ROLE.MENU_ID
	 * @return  the value of GHPORT.BASE_MENU_ROLE.MENU_ID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public String getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_MENU_ROLE.MENU_ID
	 * @param menuId  the value for GHPORT.BASE_MENU_ROLE.MENU_ID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_MENU_ROLE.OPERATING_ID
	 * @return  the value of GHPORT.BASE_MENU_ROLE.OPERATING_ID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public String getOperatingId() {
		return operatingId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_MENU_ROLE.OPERATING_ID
	 * @param operatingId  the value for GHPORT.BASE_MENU_ROLE.OPERATING_ID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public void setOperatingId(String operatingId) {
		this.operatingId = operatingId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_MENU_ROLE.CREATEDATE
	 * @return  the value of GHPORT.BASE_MENU_ROLE.CREATEDATE
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_MENU_ROLE.CREATEDATE
	 * @param createdate  the value for GHPORT.BASE_MENU_ROLE.CREATEDATE
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_MENU_ROLE.CREATEUSERREALNAME
	 * @return  the value of GHPORT.BASE_MENU_ROLE.CREATEUSERREALNAME
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public String getCreateuserrealname() {
		return createuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_MENU_ROLE.CREATEUSERREALNAME
	 * @param createuserrealname  the value for GHPORT.BASE_MENU_ROLE.CREATEUSERREALNAME
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public void setCreateuserrealname(String createuserrealname) {
		this.createuserrealname = createuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_MENU_ROLE.CREATEUSERID
	 * @return  the value of GHPORT.BASE_MENU_ROLE.CREATEUSERID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public String getCreateuserid() {
		return createuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_MENU_ROLE.CREATEUSERID
	 * @param createuserid  the value for GHPORT.BASE_MENU_ROLE.CREATEUSERID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public void setCreateuserid(String createuserid) {
		this.createuserid = createuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_MENU_ROLE.MODIFYDATE
	 * @return  the value of GHPORT.BASE_MENU_ROLE.MODIFYDATE
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_MENU_ROLE.MODIFYDATE
	 * @param modifydate  the value for GHPORT.BASE_MENU_ROLE.MODIFYDATE
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_MENU_ROLE.MODIFYUSERREALNAME
	 * @return  the value of GHPORT.BASE_MENU_ROLE.MODIFYUSERREALNAME
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public String getModifyuserrealname() {
		return modifyuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_MENU_ROLE.MODIFYUSERREALNAME
	 * @param modifyuserrealname  the value for GHPORT.BASE_MENU_ROLE.MODIFYUSERREALNAME
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public void setModifyuserrealname(String modifyuserrealname) {
		this.modifyuserrealname = modifyuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.BASE_MENU_ROLE.MODIFYUSERID
	 * @return  the value of GHPORT.BASE_MENU_ROLE.MODIFYUSERID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public String getModifyuserid() {
		return modifyuserid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.BASE_MENU_ROLE.MODIFYUSERID
	 * @param modifyuserid  the value for GHPORT.BASE_MENU_ROLE.MODIFYUSERID
	 * @abatorgenerated  Wed Mar 27 16:41:55 CST 2013
	 */
	public void setModifyuserid(String modifyuserid) {
		this.modifyuserid = modifyuserid;
	}
}