package com.gh.entity;

public class IntegrateddataWithBLOBs extends Integrateddata {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column integrateddata.DIMAGES
	 * @abatorgenerated  Mon May 11 16:23:03 CST 2015
	 */
	private String dimages;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column integrateddata.INTRODUCTION
	 * @abatorgenerated  Mon May 11 16:23:03 CST 2015
	 */
	private String introduction;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column integrateddata.FEATURE
	 * @abatorgenerated  Mon May 11 16:23:03 CST 2015
	 */
	private String feature;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column integrateddata.DIMAGES
	 * @return  the value of integrateddata.DIMAGES
	 * @abatorgenerated  Mon May 11 16:23:03 CST 2015
	 */
	public String getDimages() {
		return dimages;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column integrateddata.DIMAGES
	 * @param dimages  the value for integrateddata.DIMAGES
	 * @abatorgenerated  Mon May 11 16:23:03 CST 2015
	 */
	public void setDimages(String dimages) {
		this.dimages = dimages;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column integrateddata.INTRODUCTION
	 * @return  the value of integrateddata.INTRODUCTION
	 * @abatorgenerated  Mon May 11 16:23:03 CST 2015
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column integrateddata.INTRODUCTION
	 * @param introduction  the value for integrateddata.INTRODUCTION
	 * @abatorgenerated  Mon May 11 16:23:03 CST 2015
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column integrateddata.FEATURE
	 * @return  the value of integrateddata.FEATURE
	 * @abatorgenerated  Mon May 11 16:23:03 CST 2015
	 */
	public String getFeature() {
		return feature;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column integrateddata.FEATURE
	 * @param feature  the value for integrateddata.FEATURE
	 * @abatorgenerated  Mon May 11 16:23:03 CST 2015
	 */
	public void setFeature(String feature) {
		this.feature = feature;
	}
}