package com.gh.entity;

import java.util.Date;

public class ObPromptdata {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.OB_PROMPTDATA.FUID
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    private String fuid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.OB_PROMPTDATA.FULLNAME
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    private String fullname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.OB_PROMPTDATA.CODE
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    private String code;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.OB_PROMPTDATA.DESCRIPTION
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    private String description;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column GHPORT.OB_PROMPTDATA.CREATEDATE
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    private Date createdate;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.OB_PROMPTDATA.FUID
     *
     * @return the value of GHPORT.OB_PROMPTDATA.FUID
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    public String getFuid() {
        return fuid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.OB_PROMPTDATA.FUID
     *
     * @param fuid the value for GHPORT.OB_PROMPTDATA.FUID
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    public void setFuid(String fuid) {
        this.fuid = fuid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.OB_PROMPTDATA.FULLNAME
     *
     * @return the value of GHPORT.OB_PROMPTDATA.FULLNAME
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.OB_PROMPTDATA.FULLNAME
     *
     * @param fullname the value for GHPORT.OB_PROMPTDATA.FULLNAME
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.OB_PROMPTDATA.CODE
     *
     * @return the value of GHPORT.OB_PROMPTDATA.CODE
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.OB_PROMPTDATA.CODE
     *
     * @param code the value for GHPORT.OB_PROMPTDATA.CODE
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.OB_PROMPTDATA.DESCRIPTION
     *
     * @return the value of GHPORT.OB_PROMPTDATA.DESCRIPTION
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.OB_PROMPTDATA.DESCRIPTION
     *
     * @param description the value for GHPORT.OB_PROMPTDATA.DESCRIPTION
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column GHPORT.OB_PROMPTDATA.CREATEDATE
     *
     * @return the value of GHPORT.OB_PROMPTDATA.CREATEDATE
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column GHPORT.OB_PROMPTDATA.CREATEDATE
     *
     * @param createdate the value for GHPORT.OB_PROMPTDATA.CREATEDATE
     *
     * @abatorgenerated Wed Nov 20 13:29:06 CST 2013
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}