package com.gh.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ObVideoExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table GHPORT.OB_VIDEO
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table GHPORT.OB_VIDEO
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.OB_VIDEO
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public ObVideoExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.OB_VIDEO
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	protected ObVideoExample(ObVideoExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.OB_VIDEO
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.OB_VIDEO
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.OB_VIDEO
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.OB_VIDEO
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.OB_VIDEO
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.OB_VIDEO
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table GHPORT.OB_VIDEO
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table GHPORT.OB_VIDEO
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0 || criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andFuidIsNull() {
			addCriterion("FUID is null");
			return this;
		}

		public Criteria andFuidIsNotNull() {
			addCriterion("FUID is not null");
			return this;
		}

		public Criteria andFuidEqualTo(String value) {
			addCriterion("FUID =", value, "fuid");
			return this;
		}

		public Criteria andFuidNotEqualTo(String value) {
			addCriterion("FUID <>", value, "fuid");
			return this;
		}

		public Criteria andFuidGreaterThan(String value) {
			addCriterion("FUID >", value, "fuid");
			return this;
		}

		public Criteria andFuidGreaterThanOrEqualTo(String value) {
			addCriterion("FUID >=", value, "fuid");
			return this;
		}

		public Criteria andFuidLessThan(String value) {
			addCriterion("FUID <", value, "fuid");
			return this;
		}

		public Criteria andFuidLessThanOrEqualTo(String value) {
			addCriterion("FUID <=", value, "fuid");
			return this;
		}

		public Criteria andFuidLike(String value) {
			addCriterion("FUID like", value, "fuid");
			return this;
		}

		public Criteria andFuidNotLike(String value) {
			addCriterion("FUID not like", value, "fuid");
			return this;
		}

		public Criteria andFuidIn(List values) {
			addCriterion("FUID in", values, "fuid");
			return this;
		}

		public Criteria andFuidNotIn(List values) {
			addCriterion("FUID not in", values, "fuid");
			return this;
		}

		public Criteria andFuidBetween(String value1, String value2) {
			addCriterion("FUID between", value1, value2, "fuid");
			return this;
		}

		public Criteria andFuidNotBetween(String value1, String value2) {
			addCriterion("FUID not between", value1, value2, "fuid");
			return this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("DESCRIPTION is null");
			return this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("DESCRIPTION is not null");
			return this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("DESCRIPTION =", value, "description");
			return this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("DESCRIPTION <>", value, "description");
			return this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("DESCRIPTION >", value, "description");
			return this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION >=", value, "description");
			return this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("DESCRIPTION <", value, "description");
			return this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("DESCRIPTION <=", value, "description");
			return this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("DESCRIPTION like", value, "description");
			return this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("DESCRIPTION not like", value, "description");
			return this;
		}

		public Criteria andDescriptionIn(List values) {
			addCriterion("DESCRIPTION in", values, "description");
			return this;
		}

		public Criteria andDescriptionNotIn(List values) {
			addCriterion("DESCRIPTION not in", values, "description");
			return this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("DESCRIPTION between", value1, value2, "description");
			return this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("DESCRIPTION not between", value1, value2, "description");
			return this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("CREATEDATE is null");
			return this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("CREATEDATE is not null");
			return this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterion("CREATEDATE =", value, "createdate");
			return this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterion("CREATEDATE <>", value, "createdate");
			return this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterion("CREATEDATE >", value, "createdate");
			return this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATEDATE >=", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterion("CREATEDATE <", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterion("CREATEDATE <=", value, "createdate");
			return this;
		}

		public Criteria andCreatedateIn(List values) {
			addCriterion("CREATEDATE in", values, "createdate");
			return this;
		}

		public Criteria andCreatedateNotIn(List values) {
			addCriterion("CREATEDATE not in", values, "createdate");
			return this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterion("CREATEDATE between", value1, value2, "createdate");
			return this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterion("CREATEDATE not between", value1, value2, "createdate");
			return this;
		}

		public Criteria andModifydateIsNull() {
			addCriterion("MODIFYDATE is null");
			return this;
		}

		public Criteria andModifydateIsNotNull() {
			addCriterion("MODIFYDATE is not null");
			return this;
		}

		public Criteria andModifydateEqualTo(Date value) {
			addCriterion("MODIFYDATE =", value, "modifydate");
			return this;
		}

		public Criteria andModifydateNotEqualTo(Date value) {
			addCriterion("MODIFYDATE <>", value, "modifydate");
			return this;
		}

		public Criteria andModifydateGreaterThan(Date value) {
			addCriterion("MODIFYDATE >", value, "modifydate");
			return this;
		}

		public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
			addCriterion("MODIFYDATE >=", value, "modifydate");
			return this;
		}

		public Criteria andModifydateLessThan(Date value) {
			addCriterion("MODIFYDATE <", value, "modifydate");
			return this;
		}

		public Criteria andModifydateLessThanOrEqualTo(Date value) {
			addCriterion("MODIFYDATE <=", value, "modifydate");
			return this;
		}

		public Criteria andModifydateIn(List values) {
			addCriterion("MODIFYDATE in", values, "modifydate");
			return this;
		}

		public Criteria andModifydateNotIn(List values) {
			addCriterion("MODIFYDATE not in", values, "modifydate");
			return this;
		}

		public Criteria andModifydateBetween(Date value1, Date value2) {
			addCriterion("MODIFYDATE between", value1, value2, "modifydate");
			return this;
		}

		public Criteria andModifydateNotBetween(Date value1, Date value2) {
			addCriterion("MODIFYDATE not between", value1, value2, "modifydate");
			return this;
		}

		public Criteria andModifyuserrealnameIsNull() {
			addCriterion("MODIFYUSERREALNAME is null");
			return this;
		}

		public Criteria andModifyuserrealnameIsNotNull() {
			addCriterion("MODIFYUSERREALNAME is not null");
			return this;
		}

		public Criteria andModifyuserrealnameEqualTo(String value) {
			addCriterion("MODIFYUSERREALNAME =", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameNotEqualTo(String value) {
			addCriterion("MODIFYUSERREALNAME <>", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameGreaterThan(String value) {
			addCriterion("MODIFYUSERREALNAME >", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameGreaterThanOrEqualTo(String value) {
			addCriterion("MODIFYUSERREALNAME >=", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameLessThan(String value) {
			addCriterion("MODIFYUSERREALNAME <", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameLessThanOrEqualTo(String value) {
			addCriterion("MODIFYUSERREALNAME <=", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameLike(String value) {
			addCriterion("MODIFYUSERREALNAME like", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameNotLike(String value) {
			addCriterion("MODIFYUSERREALNAME not like", value, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameIn(List values) {
			addCriterion("MODIFYUSERREALNAME in", values, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameNotIn(List values) {
			addCriterion("MODIFYUSERREALNAME not in", values, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameBetween(String value1, String value2) {
			addCriterion("MODIFYUSERREALNAME between", value1, value2, "modifyuserrealname");
			return this;
		}

		public Criteria andModifyuserrealnameNotBetween(String value1, String value2) {
			addCriterion("MODIFYUSERREALNAME not between", value1, value2, "modifyuserrealname");
			return this;
		}

		public Criteria andCamidIsNull() {
			addCriterion("CAMID is null");
			return this;
		}

		public Criteria andCamidIsNotNull() {
			addCriterion("CAMID is not null");
			return this;
		}

		public Criteria andCamidEqualTo(String value) {
			addCriterion("CAMID =", value, "camid");
			return this;
		}

		public Criteria andCamidNotEqualTo(String value) {
			addCriterion("CAMID <>", value, "camid");
			return this;
		}

		public Criteria andCamidGreaterThan(String value) {
			addCriterion("CAMID >", value, "camid");
			return this;
		}

		public Criteria andCamidGreaterThanOrEqualTo(String value) {
			addCriterion("CAMID >=", value, "camid");
			return this;
		}

		public Criteria andCamidLessThan(String value) {
			addCriterion("CAMID <", value, "camid");
			return this;
		}

		public Criteria andCamidLessThanOrEqualTo(String value) {
			addCriterion("CAMID <=", value, "camid");
			return this;
		}

		public Criteria andCamidLike(String value) {
			addCriterion("CAMID like", value, "camid");
			return this;
		}

		public Criteria andCamidNotLike(String value) {
			addCriterion("CAMID not like", value, "camid");
			return this;
		}

		public Criteria andCamidIn(List values) {
			addCriterion("CAMID in", values, "camid");
			return this;
		}

		public Criteria andCamidNotIn(List values) {
			addCriterion("CAMID not in", values, "camid");
			return this;
		}

		public Criteria andCamidBetween(String value1, String value2) {
			addCriterion("CAMID between", value1, value2, "camid");
			return this;
		}

		public Criteria andCamidNotBetween(String value1, String value2) {
			addCriterion("CAMID not between", value1, value2, "camid");
			return this;
		}

		public Criteria andIpIsNull() {
			addCriterion("IP is null");
			return this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("IP is not null");
			return this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("IP =", value, "ip");
			return this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("IP <>", value, "ip");
			return this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("IP >", value, "ip");
			return this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("IP >=", value, "ip");
			return this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("IP <", value, "ip");
			return this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("IP <=", value, "ip");
			return this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("IP like", value, "ip");
			return this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("IP not like", value, "ip");
			return this;
		}

		public Criteria andIpIn(List values) {
			addCriterion("IP in", values, "ip");
			return this;
		}

		public Criteria andIpNotIn(List values) {
			addCriterion("IP not in", values, "ip");
			return this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("IP between", value1, value2, "ip");
			return this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("IP not between", value1, value2, "ip");
			return this;
		}

		public Criteria andPortIsNull() {
			addCriterion("PORT is null");
			return this;
		}

		public Criteria andPortIsNotNull() {
			addCriterion("PORT is not null");
			return this;
		}

		public Criteria andPortEqualTo(String value) {
			addCriterion("PORT =", value, "port");
			return this;
		}

		public Criteria andPortNotEqualTo(String value) {
			addCriterion("PORT <>", value, "port");
			return this;
		}

		public Criteria andPortGreaterThan(String value) {
			addCriterion("PORT >", value, "port");
			return this;
		}

		public Criteria andPortGreaterThanOrEqualTo(String value) {
			addCriterion("PORT >=", value, "port");
			return this;
		}

		public Criteria andPortLessThan(String value) {
			addCriterion("PORT <", value, "port");
			return this;
		}

		public Criteria andPortLessThanOrEqualTo(String value) {
			addCriterion("PORT <=", value, "port");
			return this;
		}

		public Criteria andPortLike(String value) {
			addCriterion("PORT like", value, "port");
			return this;
		}

		public Criteria andPortNotLike(String value) {
			addCriterion("PORT not like", value, "port");
			return this;
		}

		public Criteria andPortIn(List values) {
			addCriterion("PORT in", values, "port");
			return this;
		}

		public Criteria andPortNotIn(List values) {
			addCriterion("PORT not in", values, "port");
			return this;
		}

		public Criteria andPortBetween(String value1, String value2) {
			addCriterion("PORT between", value1, value2, "port");
			return this;
		}

		public Criteria andPortNotBetween(String value1, String value2) {
			addCriterion("PORT not between", value1, value2, "port");
			return this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("USERNAME is null");
			return this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("USERNAME is not null");
			return this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("USERNAME =", value, "username");
			return this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("USERNAME <>", value, "username");
			return this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("USERNAME >", value, "username");
			return this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("USERNAME >=", value, "username");
			return this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("USERNAME <", value, "username");
			return this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("USERNAME <=", value, "username");
			return this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("USERNAME like", value, "username");
			return this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("USERNAME not like", value, "username");
			return this;
		}

		public Criteria andUsernameIn(List values) {
			addCriterion("USERNAME in", values, "username");
			return this;
		}

		public Criteria andUsernameNotIn(List values) {
			addCriterion("USERNAME not in", values, "username");
			return this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("USERNAME between", value1, value2, "username");
			return this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("USERNAME not between", value1, value2, "username");
			return this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("PASSWORD is null");
			return this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("PASSWORD is not null");
			return this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("PASSWORD =", value, "password");
			return this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("PASSWORD <>", value, "password");
			return this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("PASSWORD >", value, "password");
			return this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("PASSWORD >=", value, "password");
			return this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("PASSWORD <", value, "password");
			return this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("PASSWORD <=", value, "password");
			return this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("PASSWORD like", value, "password");
			return this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("PASSWORD not like", value, "password");
			return this;
		}

		public Criteria andPasswordIn(List values) {
			addCriterion("PASSWORD in", values, "password");
			return this;
		}

		public Criteria andPasswordNotIn(List values) {
			addCriterion("PASSWORD not in", values, "password");
			return this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("PASSWORD between", value1, value2, "password");
			return this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("PASSWORD not between", value1, value2, "password");
			return this;
		}

		public Criteria andChannelIsNull() {
			addCriterion("CHANNEL is null");
			return this;
		}

		public Criteria andChannelIsNotNull() {
			addCriterion("CHANNEL is not null");
			return this;
		}

		public Criteria andChannelEqualTo(String value) {
			addCriterion("CHANNEL =", value, "channel");
			return this;
		}

		public Criteria andChannelNotEqualTo(String value) {
			addCriterion("CHANNEL <>", value, "channel");
			return this;
		}

		public Criteria andChannelGreaterThan(String value) {
			addCriterion("CHANNEL >", value, "channel");
			return this;
		}

		public Criteria andChannelGreaterThanOrEqualTo(String value) {
			addCriterion("CHANNEL >=", value, "channel");
			return this;
		}

		public Criteria andChannelLessThan(String value) {
			addCriterion("CHANNEL <", value, "channel");
			return this;
		}

		public Criteria andChannelLessThanOrEqualTo(String value) {
			addCriterion("CHANNEL <=", value, "channel");
			return this;
		}

		public Criteria andChannelLike(String value) {
			addCriterion("CHANNEL like", value, "channel");
			return this;
		}

		public Criteria andChannelNotLike(String value) {
			addCriterion("CHANNEL not like", value, "channel");
			return this;
		}

		public Criteria andChannelIn(List values) {
			addCriterion("CHANNEL in", values, "channel");
			return this;
		}

		public Criteria andChannelNotIn(List values) {
			addCriterion("CHANNEL not in", values, "channel");
			return this;
		}

		public Criteria andChannelBetween(String value1, String value2) {
			addCriterion("CHANNEL between", value1, value2, "channel");
			return this;
		}

		public Criteria andChannelNotBetween(String value1, String value2) {
			addCriterion("CHANNEL not between", value1, value2, "channel");
			return this;
		}

		public Criteria andDevtypeIsNull() {
			addCriterion("DEVTYPE is null");
			return this;
		}

		public Criteria andDevtypeIsNotNull() {
			addCriterion("DEVTYPE is not null");
			return this;
		}

		public Criteria andDevtypeEqualTo(String value) {
			addCriterion("DEVTYPE =", value, "devtype");
			return this;
		}

		public Criteria andDevtypeNotEqualTo(String value) {
			addCriterion("DEVTYPE <>", value, "devtype");
			return this;
		}

		public Criteria andDevtypeGreaterThan(String value) {
			addCriterion("DEVTYPE >", value, "devtype");
			return this;
		}

		public Criteria andDevtypeGreaterThanOrEqualTo(String value) {
			addCriterion("DEVTYPE >=", value, "devtype");
			return this;
		}

		public Criteria andDevtypeLessThan(String value) {
			addCriterion("DEVTYPE <", value, "devtype");
			return this;
		}

		public Criteria andDevtypeLessThanOrEqualTo(String value) {
			addCriterion("DEVTYPE <=", value, "devtype");
			return this;
		}

		public Criteria andDevtypeLike(String value) {
			addCriterion("DEVTYPE like", value, "devtype");
			return this;
		}

		public Criteria andDevtypeNotLike(String value) {
			addCriterion("DEVTYPE not like", value, "devtype");
			return this;
		}

		public Criteria andDevtypeIn(List values) {
			addCriterion("DEVTYPE in", values, "devtype");
			return this;
		}

		public Criteria andDevtypeNotIn(List values) {
			addCriterion("DEVTYPE not in", values, "devtype");
			return this;
		}

		public Criteria andDevtypeBetween(String value1, String value2) {
			addCriterion("DEVTYPE between", value1, value2, "devtype");
			return this;
		}

		public Criteria andDevtypeNotBetween(String value1, String value2) {
			addCriterion("DEVTYPE not between", value1, value2, "devtype");
			return this;
		}

		public Criteria andDevidIsNull() {
			addCriterion("DEVID is null");
			return this;
		}

		public Criteria andDevidIsNotNull() {
			addCriterion("DEVID is not null");
			return this;
		}

		public Criteria andDevidEqualTo(String value) {
			addCriterion("DEVID =", value, "devid");
			return this;
		}

		public Criteria andDevidNotEqualTo(String value) {
			addCriterion("DEVID <>", value, "devid");
			return this;
		}

		public Criteria andDevidGreaterThan(String value) {
			addCriterion("DEVID >", value, "devid");
			return this;
		}

		public Criteria andDevidGreaterThanOrEqualTo(String value) {
			addCriterion("DEVID >=", value, "devid");
			return this;
		}

		public Criteria andDevidLessThan(String value) {
			addCriterion("DEVID <", value, "devid");
			return this;
		}

		public Criteria andDevidLessThanOrEqualTo(String value) {
			addCriterion("DEVID <=", value, "devid");
			return this;
		}

		public Criteria andDevidLike(String value) {
			addCriterion("DEVID like", value, "devid");
			return this;
		}

		public Criteria andDevidNotLike(String value) {
			addCriterion("DEVID not like", value, "devid");
			return this;
		}

		public Criteria andDevidIn(List values) {
			addCriterion("DEVID in", values, "devid");
			return this;
		}

		public Criteria andDevidNotIn(List values) {
			addCriterion("DEVID not in", values, "devid");
			return this;
		}

		public Criteria andDevidBetween(String value1, String value2) {
			addCriterion("DEVID between", value1, value2, "devid");
			return this;
		}

		public Criteria andDevidNotBetween(String value1, String value2) {
			addCriterion("DEVID not between", value1, value2, "devid");
			return this;
		}

		public Criteria andRealtypeIsNull() {
			addCriterion("REALTYPE is null");
			return this;
		}

		public Criteria andRealtypeIsNotNull() {
			addCriterion("REALTYPE is not null");
			return this;
		}

		public Criteria andRealtypeEqualTo(BigDecimal value) {
			addCriterion("REALTYPE =", value, "realtype");
			return this;
		}

		public Criteria andRealtypeNotEqualTo(BigDecimal value) {
			addCriterion("REALTYPE <>", value, "realtype");
			return this;
		}

		public Criteria andRealtypeGreaterThan(BigDecimal value) {
			addCriterion("REALTYPE >", value, "realtype");
			return this;
		}

		public Criteria andRealtypeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("REALTYPE >=", value, "realtype");
			return this;
		}

		public Criteria andRealtypeLessThan(BigDecimal value) {
			addCriterion("REALTYPE <", value, "realtype");
			return this;
		}

		public Criteria andRealtypeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("REALTYPE <=", value, "realtype");
			return this;
		}

		public Criteria andRealtypeIn(List values) {
			addCriterion("REALTYPE in", values, "realtype");
			return this;
		}

		public Criteria andRealtypeNotIn(List values) {
			addCriterion("REALTYPE not in", values, "realtype");
			return this;
		}

		public Criteria andRealtypeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("REALTYPE between", value1, value2, "realtype");
			return this;
		}

		public Criteria andRealtypeNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("REALTYPE not between", value1, value2, "realtype");
			return this;
		}

		public Criteria andSreamipIsNull() {
			addCriterion("SREAMIP is null");
			return this;
		}

		public Criteria andSreamipIsNotNull() {
			addCriterion("SREAMIP is not null");
			return this;
		}

		public Criteria andSreamipEqualTo(String value) {
			addCriterion("SREAMIP =", value, "sreamip");
			return this;
		}

		public Criteria andSreamipNotEqualTo(String value) {
			addCriterion("SREAMIP <>", value, "sreamip");
			return this;
		}

		public Criteria andSreamipGreaterThan(String value) {
			addCriterion("SREAMIP >", value, "sreamip");
			return this;
		}

		public Criteria andSreamipGreaterThanOrEqualTo(String value) {
			addCriterion("SREAMIP >=", value, "sreamip");
			return this;
		}

		public Criteria andSreamipLessThan(String value) {
			addCriterion("SREAMIP <", value, "sreamip");
			return this;
		}

		public Criteria andSreamipLessThanOrEqualTo(String value) {
			addCriterion("SREAMIP <=", value, "sreamip");
			return this;
		}

		public Criteria andSreamipLike(String value) {
			addCriterion("SREAMIP like", value, "sreamip");
			return this;
		}

		public Criteria andSreamipNotLike(String value) {
			addCriterion("SREAMIP not like", value, "sreamip");
			return this;
		}

		public Criteria andSreamipIn(List values) {
			addCriterion("SREAMIP in", values, "sreamip");
			return this;
		}

		public Criteria andSreamipNotIn(List values) {
			addCriterion("SREAMIP not in", values, "sreamip");
			return this;
		}

		public Criteria andSreamipBetween(String value1, String value2) {
			addCriterion("SREAMIP between", value1, value2, "sreamip");
			return this;
		}

		public Criteria andSreamipNotBetween(String value1, String value2) {
			addCriterion("SREAMIP not between", value1, value2, "sreamip");
			return this;
		}

		public Criteria andStreamportIsNull() {
			addCriterion("STREAMPORT is null");
			return this;
		}

		public Criteria andStreamportIsNotNull() {
			addCriterion("STREAMPORT is not null");
			return this;
		}

		public Criteria andStreamportEqualTo(String value) {
			addCriterion("STREAMPORT =", value, "streamport");
			return this;
		}

		public Criteria andStreamportNotEqualTo(String value) {
			addCriterion("STREAMPORT <>", value, "streamport");
			return this;
		}

		public Criteria andStreamportGreaterThan(String value) {
			addCriterion("STREAMPORT >", value, "streamport");
			return this;
		}

		public Criteria andStreamportGreaterThanOrEqualTo(String value) {
			addCriterion("STREAMPORT >=", value, "streamport");
			return this;
		}

		public Criteria andStreamportLessThan(String value) {
			addCriterion("STREAMPORT <", value, "streamport");
			return this;
		}

		public Criteria andStreamportLessThanOrEqualTo(String value) {
			addCriterion("STREAMPORT <=", value, "streamport");
			return this;
		}

		public Criteria andStreamportLike(String value) {
			addCriterion("STREAMPORT like", value, "streamport");
			return this;
		}

		public Criteria andStreamportNotLike(String value) {
			addCriterion("STREAMPORT not like", value, "streamport");
			return this;
		}

		public Criteria andStreamportIn(List values) {
			addCriterion("STREAMPORT in", values, "streamport");
			return this;
		}

		public Criteria andStreamportNotIn(List values) {
			addCriterion("STREAMPORT not in", values, "streamport");
			return this;
		}

		public Criteria andStreamportBetween(String value1, String value2) {
			addCriterion("STREAMPORT between", value1, value2, "streamport");
			return this;
		}

		public Criteria andStreamportNotBetween(String value1, String value2) {
			addCriterion("STREAMPORT not between", value1, value2, "streamport");
			return this;
		}

		public Criteria andProxyipIsNull() {
			addCriterion("PROXYIP is null");
			return this;
		}

		public Criteria andProxyipIsNotNull() {
			addCriterion("PROXYIP is not null");
			return this;
		}

		public Criteria andProxyipEqualTo(String value) {
			addCriterion("PROXYIP =", value, "proxyip");
			return this;
		}

		public Criteria andProxyipNotEqualTo(String value) {
			addCriterion("PROXYIP <>", value, "proxyip");
			return this;
		}

		public Criteria andProxyipGreaterThan(String value) {
			addCriterion("PROXYIP >", value, "proxyip");
			return this;
		}

		public Criteria andProxyipGreaterThanOrEqualTo(String value) {
			addCriterion("PROXYIP >=", value, "proxyip");
			return this;
		}

		public Criteria andProxyipLessThan(String value) {
			addCriterion("PROXYIP <", value, "proxyip");
			return this;
		}

		public Criteria andProxyipLessThanOrEqualTo(String value) {
			addCriterion("PROXYIP <=", value, "proxyip");
			return this;
		}

		public Criteria andProxyipLike(String value) {
			addCriterion("PROXYIP like", value, "proxyip");
			return this;
		}

		public Criteria andProxyipNotLike(String value) {
			addCriterion("PROXYIP not like", value, "proxyip");
			return this;
		}

		public Criteria andProxyipIn(List values) {
			addCriterion("PROXYIP in", values, "proxyip");
			return this;
		}

		public Criteria andProxyipNotIn(List values) {
			addCriterion("PROXYIP not in", values, "proxyip");
			return this;
		}

		public Criteria andProxyipBetween(String value1, String value2) {
			addCriterion("PROXYIP between", value1, value2, "proxyip");
			return this;
		}

		public Criteria andProxyipNotBetween(String value1, String value2) {
			addCriterion("PROXYIP not between", value1, value2, "proxyip");
			return this;
		}

		public Criteria andProxyportIsNull() {
			addCriterion("PROXYPORT is null");
			return this;
		}

		public Criteria andProxyportIsNotNull() {
			addCriterion("PROXYPORT is not null");
			return this;
		}

		public Criteria andProxyportEqualTo(String value) {
			addCriterion("PROXYPORT =", value, "proxyport");
			return this;
		}

		public Criteria andProxyportNotEqualTo(String value) {
			addCriterion("PROXYPORT <>", value, "proxyport");
			return this;
		}

		public Criteria andProxyportGreaterThan(String value) {
			addCriterion("PROXYPORT >", value, "proxyport");
			return this;
		}

		public Criteria andProxyportGreaterThanOrEqualTo(String value) {
			addCriterion("PROXYPORT >=", value, "proxyport");
			return this;
		}

		public Criteria andProxyportLessThan(String value) {
			addCriterion("PROXYPORT <", value, "proxyport");
			return this;
		}

		public Criteria andProxyportLessThanOrEqualTo(String value) {
			addCriterion("PROXYPORT <=", value, "proxyport");
			return this;
		}

		public Criteria andProxyportLike(String value) {
			addCriterion("PROXYPORT like", value, "proxyport");
			return this;
		}

		public Criteria andProxyportNotLike(String value) {
			addCriterion("PROXYPORT not like", value, "proxyport");
			return this;
		}

		public Criteria andProxyportIn(List values) {
			addCriterion("PROXYPORT in", values, "proxyport");
			return this;
		}

		public Criteria andProxyportNotIn(List values) {
			addCriterion("PROXYPORT not in", values, "proxyport");
			return this;
		}

		public Criteria andProxyportBetween(String value1, String value2) {
			addCriterion("PROXYPORT between", value1, value2, "proxyport");
			return this;
		}

		public Criteria andProxyportNotBetween(String value1, String value2) {
			addCriterion("PROXYPORT not between", value1, value2, "proxyport");
			return this;
		}

		public Criteria andAccessipIsNull() {
			addCriterion("ACCESSIP is null");
			return this;
		}

		public Criteria andAccessipIsNotNull() {
			addCriterion("ACCESSIP is not null");
			return this;
		}

		public Criteria andAccessipEqualTo(String value) {
			addCriterion("ACCESSIP =", value, "accessip");
			return this;
		}

		public Criteria andAccessipNotEqualTo(String value) {
			addCriterion("ACCESSIP <>", value, "accessip");
			return this;
		}

		public Criteria andAccessipGreaterThan(String value) {
			addCriterion("ACCESSIP >", value, "accessip");
			return this;
		}

		public Criteria andAccessipGreaterThanOrEqualTo(String value) {
			addCriterion("ACCESSIP >=", value, "accessip");
			return this;
		}

		public Criteria andAccessipLessThan(String value) {
			addCriterion("ACCESSIP <", value, "accessip");
			return this;
		}

		public Criteria andAccessipLessThanOrEqualTo(String value) {
			addCriterion("ACCESSIP <=", value, "accessip");
			return this;
		}

		public Criteria andAccessipLike(String value) {
			addCriterion("ACCESSIP like", value, "accessip");
			return this;
		}

		public Criteria andAccessipNotLike(String value) {
			addCriterion("ACCESSIP not like", value, "accessip");
			return this;
		}

		public Criteria andAccessipIn(List values) {
			addCriterion("ACCESSIP in", values, "accessip");
			return this;
		}

		public Criteria andAccessipNotIn(List values) {
			addCriterion("ACCESSIP not in", values, "accessip");
			return this;
		}

		public Criteria andAccessipBetween(String value1, String value2) {
			addCriterion("ACCESSIP between", value1, value2, "accessip");
			return this;
		}

		public Criteria andAccessipNotBetween(String value1, String value2) {
			addCriterion("ACCESSIP not between", value1, value2, "accessip");
			return this;
		}

		public Criteria andAccessportIsNull() {
			addCriterion("ACCESSPORT is null");
			return this;
		}

		public Criteria andAccessportIsNotNull() {
			addCriterion("ACCESSPORT is not null");
			return this;
		}

		public Criteria andAccessportEqualTo(String value) {
			addCriterion("ACCESSPORT =", value, "accessport");
			return this;
		}

		public Criteria andAccessportNotEqualTo(String value) {
			addCriterion("ACCESSPORT <>", value, "accessport");
			return this;
		}

		public Criteria andAccessportGreaterThan(String value) {
			addCriterion("ACCESSPORT >", value, "accessport");
			return this;
		}

		public Criteria andAccessportGreaterThanOrEqualTo(String value) {
			addCriterion("ACCESSPORT >=", value, "accessport");
			return this;
		}

		public Criteria andAccessportLessThan(String value) {
			addCriterion("ACCESSPORT <", value, "accessport");
			return this;
		}

		public Criteria andAccessportLessThanOrEqualTo(String value) {
			addCriterion("ACCESSPORT <=", value, "accessport");
			return this;
		}

		public Criteria andAccessportLike(String value) {
			addCriterion("ACCESSPORT like", value, "accessport");
			return this;
		}

		public Criteria andAccessportNotLike(String value) {
			addCriterion("ACCESSPORT not like", value, "accessport");
			return this;
		}

		public Criteria andAccessportIn(List values) {
			addCriterion("ACCESSPORT in", values, "accessport");
			return this;
		}

		public Criteria andAccessportNotIn(List values) {
			addCriterion("ACCESSPORT not in", values, "accessport");
			return this;
		}

		public Criteria andAccessportBetween(String value1, String value2) {
			addCriterion("ACCESSPORT between", value1, value2, "accessport");
			return this;
		}

		public Criteria andAccessportNotBetween(String value1, String value2) {
			addCriterion("ACCESSPORT not between", value1, value2, "accessport");
			return this;
		}

		public Criteria andFxIsNull() {
			addCriterion("FX is null");
			return this;
		}

		public Criteria andFxIsNotNull() {
			addCriterion("FX is not null");
			return this;
		}

		public Criteria andFxEqualTo(BigDecimal value) {
			addCriterion("FX =", value, "fx");
			return this;
		}

		public Criteria andFxNotEqualTo(BigDecimal value) {
			addCriterion("FX <>", value, "fx");
			return this;
		}

		public Criteria andFxGreaterThan(BigDecimal value) {
			addCriterion("FX >", value, "fx");
			return this;
		}

		public Criteria andFxGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FX >=", value, "fx");
			return this;
		}

		public Criteria andFxLessThan(BigDecimal value) {
			addCriterion("FX <", value, "fx");
			return this;
		}

		public Criteria andFxLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FX <=", value, "fx");
			return this;
		}

		public Criteria andFxIn(List values) {
			addCriterion("FX in", values, "fx");
			return this;
		}

		public Criteria andFxNotIn(List values) {
			addCriterion("FX not in", values, "fx");
			return this;
		}

		public Criteria andFxBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FX between", value1, value2, "fx");
			return this;
		}

		public Criteria andFxNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FX not between", value1, value2, "fx");
			return this;
		}

		public Criteria andFyIsNull() {
			addCriterion("FY is null");
			return this;
		}

		public Criteria andFyIsNotNull() {
			addCriterion("FY is not null");
			return this;
		}

		public Criteria andFyEqualTo(BigDecimal value) {
			addCriterion("FY =", value, "fy");
			return this;
		}

		public Criteria andFyNotEqualTo(BigDecimal value) {
			addCriterion("FY <>", value, "fy");
			return this;
		}

		public Criteria andFyGreaterThan(BigDecimal value) {
			addCriterion("FY >", value, "fy");
			return this;
		}

		public Criteria andFyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("FY >=", value, "fy");
			return this;
		}

		public Criteria andFyLessThan(BigDecimal value) {
			addCriterion("FY <", value, "fy");
			return this;
		}

		public Criteria andFyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("FY <=", value, "fy");
			return this;
		}

		public Criteria andFyIn(List values) {
			addCriterion("FY in", values, "fy");
			return this;
		}

		public Criteria andFyNotIn(List values) {
			addCriterion("FY not in", values, "fy");
			return this;
		}

		public Criteria andFyBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FY between", value1, value2, "fy");
			return this;
		}

		public Criteria andFyNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("FY not between", value1, value2, "fy");
			return this;
		}

		public Criteria andFullnameIsNull() {
			addCriterion("FULLNAME is null");
			return this;
		}

		public Criteria andFullnameIsNotNull() {
			addCriterion("FULLNAME is not null");
			return this;
		}

		public Criteria andFullnameEqualTo(String value) {
			addCriterion("FULLNAME =", value, "fullname");
			return this;
		}

		public Criteria andFullnameNotEqualTo(String value) {
			addCriterion("FULLNAME <>", value, "fullname");
			return this;
		}

		public Criteria andFullnameGreaterThan(String value) {
			addCriterion("FULLNAME >", value, "fullname");
			return this;
		}

		public Criteria andFullnameGreaterThanOrEqualTo(String value) {
			addCriterion("FULLNAME >=", value, "fullname");
			return this;
		}

		public Criteria andFullnameLessThan(String value) {
			addCriterion("FULLNAME <", value, "fullname");
			return this;
		}

		public Criteria andFullnameLessThanOrEqualTo(String value) {
			addCriterion("FULLNAME <=", value, "fullname");
			return this;
		}

		public Criteria andFullnameLike(String value) {
			addCriterion("FULLNAME like", value, "fullname");
			return this;
		}

		public Criteria andFullnameNotLike(String value) {
			addCriterion("FULLNAME not like", value, "fullname");
			return this;
		}

		public Criteria andFullnameIn(List values) {
			addCriterion("FULLNAME in", values, "fullname");
			return this;
		}

		public Criteria andFullnameNotIn(List values) {
			addCriterion("FULLNAME not in", values, "fullname");
			return this;
		}

		public Criteria andFullnameBetween(String value1, String value2) {
			addCriterion("FULLNAME between", value1, value2, "fullname");
			return this;
		}

		public Criteria andFullnameNotBetween(String value1, String value2) {
			addCriterion("FULLNAME not between", value1, value2, "fullname");
			return this;
		}
	}
}