package com.gh.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ObVideo {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.FUID
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String fuid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.DESCRIPTION
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String description;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.CREATEDATE
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private Date createdate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.MODIFYDATE
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private Date modifydate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.MODIFYUSERREALNAME
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String modifyuserrealname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.CAMID
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String camid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.IP
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String ip;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.PORT
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String port;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.USERNAME
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String username;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.PASSWORD
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String password;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.CHANNEL
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String channel;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.DEVTYPE
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String devtype;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.DEVID
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String devid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.REALTYPE
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private BigDecimal realtype;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.SREAMIP
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String sreamip;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.STREAMPORT
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String streamport;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.PROXYIP
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String proxyip;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.PROXYPORT
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String proxyport;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.ACCESSIP
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String accessip;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.ACCESSPORT
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String accessport;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.FX
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private BigDecimal fx;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.FY
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private BigDecimal fy;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column GHPORT.OB_VIDEO.FULLNAME
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	private String fullname;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.FUID
	 * @return  the value of GHPORT.OB_VIDEO.FUID
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getFuid() {
		return fuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.FUID
	 * @param fuid  the value for GHPORT.OB_VIDEO.FUID
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setFuid(String fuid) {
		this.fuid = fuid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.DESCRIPTION
	 * @return  the value of GHPORT.OB_VIDEO.DESCRIPTION
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.DESCRIPTION
	 * @param description  the value for GHPORT.OB_VIDEO.DESCRIPTION
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.CREATEDATE
	 * @return  the value of GHPORT.OB_VIDEO.CREATEDATE
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.CREATEDATE
	 * @param createdate  the value for GHPORT.OB_VIDEO.CREATEDATE
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.MODIFYDATE
	 * @return  the value of GHPORT.OB_VIDEO.MODIFYDATE
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.MODIFYDATE
	 * @param modifydate  the value for GHPORT.OB_VIDEO.MODIFYDATE
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.MODIFYUSERREALNAME
	 * @return  the value of GHPORT.OB_VIDEO.MODIFYUSERREALNAME
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getModifyuserrealname() {
		return modifyuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.MODIFYUSERREALNAME
	 * @param modifyuserrealname  the value for GHPORT.OB_VIDEO.MODIFYUSERREALNAME
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setModifyuserrealname(String modifyuserrealname) {
		this.modifyuserrealname = modifyuserrealname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.CAMID
	 * @return  the value of GHPORT.OB_VIDEO.CAMID
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getCamid() {
		return camid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.CAMID
	 * @param camid  the value for GHPORT.OB_VIDEO.CAMID
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setCamid(String camid) {
		this.camid = camid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.IP
	 * @return  the value of GHPORT.OB_VIDEO.IP
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.IP
	 * @param ip  the value for GHPORT.OB_VIDEO.IP
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.PORT
	 * @return  the value of GHPORT.OB_VIDEO.PORT
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getPort() {
		return port;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.PORT
	 * @param port  the value for GHPORT.OB_VIDEO.PORT
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setPort(String port) {
		this.port = port;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.USERNAME
	 * @return  the value of GHPORT.OB_VIDEO.USERNAME
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.USERNAME
	 * @param username  the value for GHPORT.OB_VIDEO.USERNAME
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.PASSWORD
	 * @return  the value of GHPORT.OB_VIDEO.PASSWORD
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.PASSWORD
	 * @param password  the value for GHPORT.OB_VIDEO.PASSWORD
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.CHANNEL
	 * @return  the value of GHPORT.OB_VIDEO.CHANNEL
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getChannel() {
		return channel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.CHANNEL
	 * @param channel  the value for GHPORT.OB_VIDEO.CHANNEL
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setChannel(String channel) {
		this.channel = channel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.DEVTYPE
	 * @return  the value of GHPORT.OB_VIDEO.DEVTYPE
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getDevtype() {
		return devtype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.DEVTYPE
	 * @param devtype  the value for GHPORT.OB_VIDEO.DEVTYPE
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setDevtype(String devtype) {
		this.devtype = devtype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.DEVID
	 * @return  the value of GHPORT.OB_VIDEO.DEVID
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getDevid() {
		return devid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.DEVID
	 * @param devid  the value for GHPORT.OB_VIDEO.DEVID
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setDevid(String devid) {
		this.devid = devid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.REALTYPE
	 * @return  the value of GHPORT.OB_VIDEO.REALTYPE
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public BigDecimal getRealtype() {
		return realtype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.REALTYPE
	 * @param realtype  the value for GHPORT.OB_VIDEO.REALTYPE
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setRealtype(BigDecimal realtype) {
		this.realtype = realtype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.SREAMIP
	 * @return  the value of GHPORT.OB_VIDEO.SREAMIP
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getSreamip() {
		return sreamip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.SREAMIP
	 * @param sreamip  the value for GHPORT.OB_VIDEO.SREAMIP
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setSreamip(String sreamip) {
		this.sreamip = sreamip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.STREAMPORT
	 * @return  the value of GHPORT.OB_VIDEO.STREAMPORT
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getStreamport() {
		return streamport;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.STREAMPORT
	 * @param streamport  the value for GHPORT.OB_VIDEO.STREAMPORT
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setStreamport(String streamport) {
		this.streamport = streamport;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.PROXYIP
	 * @return  the value of GHPORT.OB_VIDEO.PROXYIP
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getProxyip() {
		return proxyip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.PROXYIP
	 * @param proxyip  the value for GHPORT.OB_VIDEO.PROXYIP
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setProxyip(String proxyip) {
		this.proxyip = proxyip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.PROXYPORT
	 * @return  the value of GHPORT.OB_VIDEO.PROXYPORT
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getProxyport() {
		return proxyport;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.PROXYPORT
	 * @param proxyport  the value for GHPORT.OB_VIDEO.PROXYPORT
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setProxyport(String proxyport) {
		this.proxyport = proxyport;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.ACCESSIP
	 * @return  the value of GHPORT.OB_VIDEO.ACCESSIP
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getAccessip() {
		return accessip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.ACCESSIP
	 * @param accessip  the value for GHPORT.OB_VIDEO.ACCESSIP
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setAccessip(String accessip) {
		this.accessip = accessip;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.ACCESSPORT
	 * @return  the value of GHPORT.OB_VIDEO.ACCESSPORT
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getAccessport() {
		return accessport;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.ACCESSPORT
	 * @param accessport  the value for GHPORT.OB_VIDEO.ACCESSPORT
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setAccessport(String accessport) {
		this.accessport = accessport;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.FX
	 * @return  the value of GHPORT.OB_VIDEO.FX
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public BigDecimal getFx() {
		return fx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.FX
	 * @param fx  the value for GHPORT.OB_VIDEO.FX
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setFx(BigDecimal fx) {
		this.fx = fx;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.FY
	 * @return  the value of GHPORT.OB_VIDEO.FY
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public BigDecimal getFy() {
		return fy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.FY
	 * @param fy  the value for GHPORT.OB_VIDEO.FY
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setFy(BigDecimal fy) {
		this.fy = fy;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column GHPORT.OB_VIDEO.FULLNAME
	 * @return  the value of GHPORT.OB_VIDEO.FULLNAME
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column GHPORT.OB_VIDEO.FULLNAME
	 * @param fullname  the value for GHPORT.OB_VIDEO.FULLNAME
	 * @abatorgenerated  Thu Nov 14 10:21:32 CST 2013
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}
}