package com.gh.dao;

import com.gh.entity.Integrateddata;
import com.gh.entity.IntegrateddataExample;
import com.gh.entity.IntegrateddataWithBLOBs;
import java.util.List;

public interface IntegrateddataDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table integrateddata
     *
     * @abatorgenerated Fri Dec 19 17:07:43 CST 2014
     */
    void insert(IntegrateddataWithBLOBs record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table integrateddata
     *
     * @abatorgenerated Fri Dec 19 17:07:43 CST 2014
     */
    List selectByExampleWithoutBLOBs(IntegrateddataExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table integrateddata
     *
     * @abatorgenerated Fri Dec 19 17:07:43 CST 2014
     */
    List selectByExampleWithBLOBs(IntegrateddataExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table integrateddata
     *
     * @abatorgenerated Fri Dec 19 17:07:43 CST 2014
     */
    int deleteByExample(IntegrateddataExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table integrateddata
     *
     * @abatorgenerated Fri Dec 19 17:07:43 CST 2014
     */
    int countByExample(IntegrateddataExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table integrateddata
     *
     * @abatorgenerated Fri Dec 19 17:07:43 CST 2014
     */
    int updateByExampleSelective(IntegrateddataWithBLOBs record, IntegrateddataExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table integrateddata
     *
     * @abatorgenerated Fri Dec 19 17:07:43 CST 2014
     */
    int updateByExample(IntegrateddataWithBLOBs record, IntegrateddataExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table integrateddata
     *
     * @abatorgenerated Fri Dec 19 17:07:43 CST 2014
     */
    int updateByExample(Integrateddata record, IntegrateddataExample example);
    public List<Integrateddata> execSql(String sql);
    
    public List<IntegrateddataWithBLOBs> IntegratedQueryByPage(int pageIndex, int pageSize, String strWhere, String strOrderBy, String x, String y);
    public List<IntegrateddataWithBLOBs> SimpleIntegratedQueryByPage(int pageIndex, int pageSize, String strWhere, String strOrderBy);
    public int getCount(String where);
}